#! /bin/sh

# Previously, FastCap-2.0wr was versioned by a date code.  The
# present framework requires a "1.2.3" format for version.  We'll keep
# 2.0 for major/minor, and increment the release.  The 032820
# distribution is release number 13.

release_num=13

echo 2.0.$release_num

