#! /bin/sh

# Previously, FastCap-2.0wr was versioned by a date code.  The
# present framework requires a "1.2.3" format for version.  We'll keep
# 2.0 for major/minor, and increment the release.  The 011517
# distribution is release number 11.

release_num=11

echo 2.0.$release_num

