#! /bin/sh

program=mrouter
version=`../version`

inno="/inno-5.5.1"
utod=u2d

srcdir=..
topdir=data

rm -rf $topdir
mkdir $topdir
mkdir $topdir/bin
mkdir $topdir/doc
mkdir $topdir/doc/xic
mkdir $topdir/examples
mkdir $topdir/examples/osu35
mkdir $topdir/examples/xic
mkdir $topdir/include
mkdir $topdir/lib

install -sc -m 0755 $srcdir/mrouter/mrouter.exe $topdir/bin

cp -f $srcdir/doc/mrmanual-$version.pdf         $topdir/doc
cp -f $srcdir/doc/mrmanual-html-$version.tar.gz $topdir/doc
cp -f $srcdir/doc/README                        $topdir/doc
cp -f $srcdir/doc/xic/MRouter.hlp               $topdir/doc/xic

$utod $topdir/doc/README
rm -f $topdir/doc/*~
$utod $topdir/doc/xic/MRouter.hlp
rm -f $topdir/doc/xic/*~

cp -f $srcdir/examples/Makefile                 $topdir/examples
cp -f $srcdir/examples/main-plg.cc              $topdir/examples
cp -f $srcdir/examples/map9v3.def               $topdir/examples
cp -f $srcdir/examples/map9v3_blk.def           $topdir/examples
cp -f $srcdir/examples/map9v3.rsc               $topdir/examples
cp -f $srcdir/examples/openMSP430.def           $topdir/examples
cp -f $srcdir/examples/openMSP430_blk.def       $topdir/examples
cp -f $srcdir/examples/openMSP430.rsc           $topdir/examples
cp -f $srcdir/examples/README                   $topdir/examples
cp -f $srcdir/examples/osu35/osu035_stdcells.gds2 $topdir/examples/osu35
cp -f $srcdir/examples/osu35/osu035_stdcells.lef  $topdir/examples/osu35
cp -f $srcdir/examples/xic/exroute.scr          $topdir/examples/xic
cp -f $srcdir/examples/xic/osu35.lib            $topdir/examples/xic
cp -f $srcdir/examples/xic/README               $topdir/examples/xic
cp -f $srcdir/examples/xic/stdvia.scr           $topdir/examples/xic
cp -f $srcdir/examples/xic/stdvias              $topdir/examples/xic
cp -f $srcdir/examples/xic/xic_tech             $topdir/examples/xic

$utod $topdir/examples/*
rm -f $topdir/examples/*~
$utod $topdir/examples/osu35/*.lef
rm -f $topdir/examples/osu35/*~
$utod $topdir/examples/xic/*
rm -f $topdir/examples/xic/*~

cp -f $srcdir/include/ld_util.h                 $topdir/include
cp -f $srcdir/include/ld_vers.h                 $topdir/include
cp -f $srcdir/include/lddb.h                    $topdir/include
cp -f $srcdir/include/mr_vers.h                 $topdir/include
cp -f $srcdir/include/mrouter.h                 $topdir/include

$utod $topdir/include/*
rm -f $topdir/include/*~

cp -f $srcdir/mrouter/libmrouter.dll            $topdir/lib

sed -e s/VERSION/$version/ < package.iss.in > package.iss
$utod package.iss

$inno/iscc package.iss > build.log
if [ $? != 0 ]; then
    echo Compile failed!
    exit 1
fi

mv Output/*.exe .
rmdir Output
echo Done

