#! /bin/sh

# Create the Makefile by copying the template and substituting text.

# jj
SOURCE=jj.va
MODELNAME=jj
MODULE=jj
KEY=b
LEVEL=2
ADD_M=no
LIMITING=no
FLAGS="\"DV_JJSTEP | DV_JJPMDC | DV_NODIST\""

cat ../../Makefile | sed \
  -e "s%^SOURCE = .*%SOURCE = $SOURCE%" \
  -e "s%^MODELNAME = .*%MODELNAME = $MODELNAME%" \
  -e "s%^MODULE = .*%MODULE = $MODULE%" \
  -e "s%^KEY = .*%KEY = $KEY%" \
  -e "s%^LEVEL = .*%LEVEL = $LEVEL%" \
  -e "s%^ADD_M = .*%ADD_M = $ADD_M%" \
  -e "s%^LIMITING = .*%LIMITING = $LIMITING%" \
  -e "s%^FLAGS = .*%FLAGS = $FLAGS%" \
  > Makefile

