
/*========================================================================*
 *                                                                        *
 *  Whiteley Research Inc, Sunnyvale, CA USA, http://wrcad.com            *
 *  Copyright (C) 2017 Whiteley Research Inc, all rights reserved.        *
 *                                                                        *
 *  Licensed under the Apache License, Version 2.0 (the "License");       *
 *  you may not use this file except in compliance with the License.      *
 *  You may obtain a copy of the License at                               *
 *                                                                        *
 *        http://www.apache.org/licenses/LICENSE-2.0                      *
 *                                                                        *
 *  See the License for the specific language governing permissions       *
 *  and limitations under the License.                                    *
 *                                                                        *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      *
 *   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES      *
 *   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-        *
 *   INFRINGEMENT.  IN NO EVENT SHALL WHITELEY RESEARCH INCORPORATED      *
 *   OR STEPHEN R. WHITELEY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER     *
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,      *
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE       *
 *   USE OR OTHER DEALINGS IN THE SOFTWARE.                               *
 *                                                                        *
 *========================================================================*
 *               XicTools Integrated Circuit Design System                *
 *                                                                        *
 * WRspice Circuit Simulation and Analysis Tool:  Device Library          *
 *                                                                        *
 *========================================================================*
 $Id:$
 *========================================================================*/

/**********
Copyright 1990 Regents of the University of California.  All rights reserved.
Author: 1998 Samuel Fung, Dennis Sinitsky and Stephen Tang
File: b3soi.c          98/5/01
Modified by Pin Su and Jan Feng	99/2/15 
Modified by Pin Su 99/4/30
Modified by Wei Jin 99/9/27
Modified by Pin Su 00/3/1
Modified by Pin Su 01/2/15
Modified by Pin Su 02/3/5
Modified by Pin Su 02/5/20
Revision 3.0 2/5/20  Pin Su 
BSIMSOI3.0 release
**********/

#include "b3sdefs.h"


namespace {

IFparm B3SOIpTable[] = {
IO("l",                 B3SOI_L,            IF_REAL | IF_LEN,
                "Length"),
IO("w",                 B3SOI_W,            IF_REAL | IF_LEN,
                "Width"),
IO("ad",                B3SOI_AD,           IF_REAL | IF_AREA,
                "Drain area"),
IO("as",                B3SOI_AS,           IF_REAL | IF_AREA,
                "Source area"),
IO("pd",                B3SOI_PD,           IF_REAL | IF_LEN,
                "Drain perimeter"),
IO("ps",                B3SOI_PS,           IF_REAL | IF_LEN,
                "Source perimeter"),
IO("nrd",               B3SOI_NRD,          IF_REAL,
                "Number of squares in drain"),
IO("nrs",               B3SOI_NRS,          IF_REAL,
                "Number of squares in source"),
IO("off",               B3SOI_OFF,          IF_FLAG,
                "Device is initially off"),
IP("ic",                B3SOI_IC,           IF_REALVEC | IF_VOLT,
                "Vector of DS,GS,BS initial voltages"),
OP("gmbs",              B3SOI_GMBS,         IF_REAL | IF_COND,
                "Gmb"),
OP("gm",                B3SOI_GM,           IF_REAL | IF_COND,
                "Gm"),
OP("gm/ids",            B3SOI_GMID,         IF_REAL,
                "Gm/Ids"),
OP("gds",               B3SOI_GDS,          IF_REAL | IF_COND,
                "Gds"),
OP("vdsat",             B3SOI_VDSAT,        IF_REAL | IF_VOLT,
                "Vdsat"),
OP("vth",               B3SOI_VON,          IF_REAL | IF_VOLT,
                "Vth"),
OP("ids",               B3SOI_CD,           IF_REAL | IF_AMP,
                "Ids"),
OP("vbs",               B3SOI_VBS,          IF_REAL | IF_VOLT,
                "Vbs"),
OP("vgs",               B3SOI_VGS,          IF_REAL | IF_VOLT,
                "Vgs"),
OP("vds",               B3SOI_VDS,          IF_REAL | IF_VOLT,
                "Vds"),
OP("ves",               B3SOI_VES,          IF_REAL | IF_VOLT,
                "Ves"),
IO("bjtoff",            B3SOI_BJTOFF,       IF_INTEGER,
                "BJT on/off flag"),
IO("debug",             B3SOI_DEBUG,        IF_INTEGER,
                "BJT on/off flag"),
IO("rth0",              B3SOI_RTH0,         IF_REAL,
                "Instance Thermal Resistance"),
IO("cth0",              B3SOI_CTH0,         IF_REAL,
                "Instance Thermal Capacitance"),
IO("nrb",               B3SOI_NRB,          IF_REAL,
                "Number of squares in body"),
IO("frbody",            B3SOI_FRBODY,       IF_REAL,
                "Layout dependent body-resistance coefficient"),

IO("nbc",               B3SOI_NBC,          IF_REAL,
                "Number of body contact isolation edge"),
IO("nseg",              B3SOI_NSEG,         IF_REAL,
                "Number segments for width partitioning"),
IO("pdbcp",             B3SOI_PDBCP,        IF_REAL | IF_LEN,
                "Perimeter length for bc parasitics at drain side"),
IO("psbcp",             B3SOI_PSBCP,        IF_REAL | IF_LEN,
                "Perimeter length for bc parasitics at source side"),
IO("agbcp",             B3SOI_AGBCP,        IF_REAL | IF_AREA,
                "Gate to body overlap area for bc parasitics"),
IO("aebcp",             B3SOI_AEBCP,        IF_REAL | IF_AREA,
                "Substrate to body overlap area for bc prasitics"),
IO("vbsusr",            B3SOI_VBSUSR,       IF_REAL | IF_VOLT,
                "Vbs specified by user"),
IO("tnodeout",          B3SOI_TNODEOUT,     IF_FLAG,
                "Flag indicating external temp node"),

// SRW - added
OP("id",                B3SOI_CD,           IF_REAL|IF_AMP,
                "Ids"),
OP("cd",                B3SOI_ID,           IF_REAL|IF_AMP|IF_USEALL,
                "Drain current"),
OP("cs",                B3SOI_IS,           IF_REAL|IF_AMP|IF_USEALL,
                "Source current"),
OP("cg",                B3SOI_IG,           IF_REAL|IF_AMP|IF_USEALL,
                "Gate current"),
OP("cb",                B3SOI_IB,           IF_REAL|IF_AMP|IF_USEALL,
                "Back-gate current"),
OP("ce",                B3SOI_IE,           IF_REAL|IF_AMP|IF_USEALL,
                "Substrate current"),
OP("icvbs",             B3SOI_IC_VBS,       IF_REAL|IF_VOLT,
                "Vbs initial condition"),
OP("icvds",             B3SOI_IC_VDS,       IF_REAL|IF_VOLT,
                "Vds initial condition"),
OP("icvgs",             B3SOI_IC_VGS,       IF_REAL|IF_VOLT,
                "Vgs initial condition"),
OP("icves",             B3SOI_IC_VES,       IF_REAL|IF_VOLT,
                "Ves initial condition"),
OP("icvps",             B3SOI_IC_VPS,       IF_REAL|IF_VOLT,
                "Vps initial condition"),
OP("dnode",             B3SOI_DNODE,        IF_INTEGER,
                "Drain node"),
OP("gnode",             B3SOI_GNODE,        IF_INTEGER,
                "Gate node"),
OP("snode",             B3SOI_SNODE,        IF_INTEGER,
                "Source node"),
OP("bnode",             B3SOI_BNODE,        IF_INTEGER,
                "Substrate node"),
OP("enode",             B3SOI_ENODE,        IF_INTEGER,
                "Body node"),
OP("dnodeprime",        B3SOI_DNODEPRIME,   IF_INTEGER,
                "Internal drain node"),
OP("snodeprime",        B3SOI_SNODEPRIME,   IF_INTEGER,
                "Internal source node"),
OP("sourceconductance", B3SOI_SOURCECONDUCT,IF_REAL|IF_COND,
                "Source conductance"),
OP("drainconductance",  B3SOI_DRAINCONDUCT, IF_REAL|IF_COND,
                "Drain conductance"),
OP("vbd",               B3SOI_VBD,          IF_REAL|IF_VOLT,
                "Vbd"),
OP("cbs",               B3SOI_CBS,          IF_REAL|IF_AMP,
                "Ibs"),
OP("cbd",               B3SOI_CBD,          IF_REAL|IF_AMP,
                "Ibd"),
OP("gbd",               B3SOI_GBD,          IF_REAL|IF_COND,
                "Gbd"),
OP("gbs",               B3SOI_GBS,          IF_REAL|IF_COND,
                "Gbs"),
OP("qb",                B3SOI_QB,           IF_REAL|IF_CHARGE,
                "Qb"),
OP("cqb",               B3SOI_CQB,          IF_REAL|IF_AMP,
                "Iqb"),
OP("qg",                B3SOI_QG,           IF_REAL|IF_CHARGE,
                "Qg"),
OP("cqg",               B3SOI_CQG,          IF_REAL|IF_AMP,
                "Iqg"),
OP("qd",                B3SOI_QD,           IF_REAL|IF_CHARGE,
                "Qd"),
OP("cqd",               B3SOI_CQD,          IF_REAL|IF_AMP,
                "Iqd"),
OP("cgg",               B3SOI_CGG,          IF_REAL|IF_AMP,
                "Cgg"),
OP("cgd",               B3SOI_CGD,          IF_REAL|IF_AMP,
                "Cgd"),
OP("cgs",               B3SOI_CGS,          IF_REAL|IF_AMP,
                "Cgs"),
OP("cdg",               B3SOI_CDG,          IF_REAL|IF_AMP,
                "Cdg"),
OP("cdd",               B3SOI_CDD,          IF_REAL|IF_AMP,
                "Cdd"),
OP("cds",               B3SOI_CDS,          IF_REAL|IF_AMP,
                "Cds"),
OP("cbg",               B3SOI_CBG,          IF_REAL|IF_AMP,
                "Cbg"),
OP("cbdb",              B3SOI_CBDB,         IF_REAL|IF_AMP,
                "Cbdb"),
OP("cbsb",              B3SOI_CBSB,         IF_REAL|IF_AMP,
                "Cbsb"),
OP("qbs",               B3SOI_QBS,          IF_REAL|IF_CHARGE,
                "Qbs"),
OP("qbd",               B3SOI_QBD,          IF_REAL|IF_CHARGE,
                "Qbd")
};

IFparm B3SOImPTable[] = {
IO("capmod",            B3SOI_MOD_CAPMOD,   IF_INTEGER,
                "Capacitance model selector"),
IO("mobmod",            B3SOI_MOD_MOBMOD,   IF_INTEGER,
                "Mobility model selector"),
IO("noimod",            B3SOI_MOD_NOIMOD,   IF_INTEGER,
                "Noise model selector"),
IO("paramchk",          B3SOI_MOD_PARAMCHK, IF_INTEGER,
                "Model parameter checking selector"),
IO("binunit",           B3SOI_MOD_BINUNIT,  IF_INTEGER,
                "Bin  unit  selector"),
IO("version",           B3SOI_MOD_VERSION,  IF_REAL,
                "Parameter for model version"),
IO("tox",               B3SOI_MOD_TOX,      IF_REAL,
                "Gate oxide thickness in meters"),
IO("dtoxcv",            B3SOI_MOD_DTOXCV,   IF_REAL,
                "Delta oxide thickness in meters in CapMod3"),

IO("cdsc",              B3SOI_MOD_CDSC,     IF_REAL,
                "Drain/Source and channel coupling capacitance"),
IO("cdscb",             B3SOI_MOD_CDSCB,    IF_REAL,
                "Body-bias dependence of cdsc"),
IO("cdscd",             B3SOI_MOD_CDSCD,    IF_REAL,
                "Drain-bias dependence of cdsc"),
IO("cit",               B3SOI_MOD_CIT,      IF_REAL,
                "Interface state capacitance"),
IO("nfactor",           B3SOI_MOD_NFACTOR,  IF_REAL,
                "Subthreshold swing Coefficient"),
IO("vsat",              B3SOI_MOD_VSAT,     IF_REAL,
                "Saturation velocity at tnom"),
IO("at",                B3SOI_MOD_AT,       IF_REAL,
                "Temperature coefficient of vsat"),
IO("a0",                B3SOI_MOD_A0,       IF_REAL,
                "Non-uniform depletion width effect coefficient."),
IO("ags",               B3SOI_MOD_AGS,      IF_REAL,
                "Gate bias  coefficient of Abulk."),
IO("a1",                B3SOI_MOD_A1,       IF_REAL,
                "Non-saturation effect coefficient"),
IO("a2",                B3SOI_MOD_A2,       IF_REAL,
                "Non-saturation effect coefficient"),
IO("keta",              B3SOI_MOD_KETA,     IF_REAL,
                "Body-bias coefficient of non-uniform depletion width effect."),
IO("nsub",              B3SOI_MOD_NSUB,     IF_REAL,
                "Substrate doping concentration with polarity"),
IO("nch",               B3SOI_MOD_NPEAK,    IF_REAL,
                "Channel doping concentration"),
IO("ngate",             B3SOI_MOD_NGATE,    IF_REAL,
                "Poly-gate doping concentration"),
IO("gamma1",            B3SOI_MOD_GAMMA1,   IF_REAL,
                "Vth body coefficient"),
IO("gamma2",            B3SOI_MOD_GAMMA2,   IF_REAL,
                "Vth body coefficient"),
IO("vbx",               B3SOI_MOD_VBX,      IF_REAL,
                "Vth transition body Voltage"),
IO("vbm",               B3SOI_MOD_VBM,      IF_REAL,
                "Maximum body voltage"),

IO("xt",                B3SOI_MOD_XT,       IF_REAL,
                "Doping depth"),
IO("k1",                B3SOI_MOD_K1,       IF_REAL,
                "Bulk effect coefficient 1"),
IO("kt1",               B3SOI_MOD_KT1,      IF_REAL,
                "Temperature coefficient of Vth"),
IO("kt1l",              B3SOI_MOD_KT1L,     IF_REAL,
                "Temperature coefficient of Vth"),
IO("kt2",               B3SOI_MOD_KT2,      IF_REAL,
                "Body-coefficient of kt1"),
IO("k2",                B3SOI_MOD_K2,       IF_REAL,
                "Bulk effect coefficient 2"),
IO("k3",                B3SOI_MOD_K3,       IF_REAL,
                "Narrow width effect coefficient"),
IO("k3b",               B3SOI_MOD_K3B,      IF_REAL,
                "Body effect coefficient of k3"),
IO("w0",                B3SOI_MOD_W0,       IF_REAL,
                "Narrow width effect parameter"),
IO("nlx",               B3SOI_MOD_NLX,      IF_REAL,
                "Lateral non-uniform doping effect"),
IO("dvt0",              B3SOI_MOD_DVT0,     IF_REAL,
                "Short channel effect coeff. 0"),
IO("dvt1",              B3SOI_MOD_DVT1,     IF_REAL,
                "Short channel effect coeff. 1"),
IO("dvt2",              B3SOI_MOD_DVT2,     IF_REAL,
                "Short channel effect coeff. 2"),
IO("dvt0w",             B3SOI_MOD_DVT0W,    IF_REAL,
                "Narrow Width coeff. 0"),
IO("dvt1w",             B3SOI_MOD_DVT1W,    IF_REAL,
                "Narrow Width effect coeff. 1"),
IO("dvt2w",             B3SOI_MOD_DVT2W,    IF_REAL,
                "Narrow Width effect coeff. 2"),
IO("drout",             B3SOI_MOD_DROUT,    IF_REAL,
                "DIBL coefficient of output resistance"),
IO("dsub",              B3SOI_MOD_DSUB,     IF_REAL,
                "DIBL coefficient in the subthreshold region"),
IO("vth0",              B3SOI_MOD_VTH0,     IF_REAL,
                "Threshold voltage"),
IO("vtho",              B3SOI_MOD_VTH0,     IF_REAL,
                "Threshold voltage"),
IO("ua",                B3SOI_MOD_UA,       IF_REAL,
                "Linear gate dependence of mobility"),
IO("ua1",               B3SOI_MOD_UA1,      IF_REAL,
                "Temperature coefficient of ua"),
IO("ub",                B3SOI_MOD_UB,       IF_REAL,
                "Quadratic gate dependence of mobility"),
IO("ub1",               B3SOI_MOD_UB1,      IF_REAL,
                "Temperature coefficient of ub"),
IO("uc",                B3SOI_MOD_UC,       IF_REAL,
                "Body-bias dependence of mobility"),
IO("uc1",               B3SOI_MOD_UC1,      IF_REAL,
                "Temperature coefficient of uc"),
IO("u0",                B3SOI_MOD_U0,       IF_REAL,
                "Low-field mobility at Tnom"),
IO("ute",               B3SOI_MOD_UTE,      IF_REAL,
                "Temperature coefficient of mobility"),
IO("voff",              B3SOI_MOD_VOFF,     IF_REAL,
                "Threshold voltage offset"),
IO("tnom",              B3SOI_MOD_TNOM,     IF_REAL,
                "Parameter measurement temperature"),
IO("cgso",              B3SOI_MOD_CGSO,     IF_REAL,
                "Gate-source overlap capacitance per width"),
IO("cgdo",              B3SOI_MOD_CGDO,     IF_REAL,
                "Gate-drain overlap capacitance per width"),
IO("xpart",             B3SOI_MOD_XPART,    IF_REAL,
                "Channel charge partitioning"),
IO("delta",             B3SOI_MOD_DELTA,    IF_REAL,
                "Effective Vds parameter"),
IO("rsh",               B3SOI_MOD_RSH,      IF_REAL,
                "Source-drain sheet resistance"),
IO("rdsw",              B3SOI_MOD_RDSW,     IF_REAL,
                "Source-drain resistance per width"),

IO("prwg",              B3SOI_MOD_PRWG,     IF_REAL,
                "Gate-bias effect on parasitic resistance"),
IO("prwb",              B3SOI_MOD_PRWB,     IF_REAL,
                "Body-effect on parasitic resistance"),

IO("prt",               B3SOI_MOD_PRT,      IF_REAL,
                "Temperature coefficient of parasitic resistance"),
IO("eta0",              B3SOI_MOD_ETA0,     IF_REAL,
                "Subthreshold region DIBL coefficient"),
IO("etab",              B3SOI_MOD_ETAB,     IF_REAL,
                "Subthreshold region DIBL coefficient"),
IO("pclm",              B3SOI_MOD_PCLM,     IF_REAL,
                "Channel length modulation Coefficient"),
IO("pdiblc1",           B3SOI_MOD_PDIBL1,   IF_REAL,
                "Drain-induced barrier lowering coefficient"),
IO("pdiblc2",           B3SOI_MOD_PDIBL2,   IF_REAL,
                "Drain-induced barrier lowering coefficient"),
IO("pdiblcb",           B3SOI_MOD_PDIBLB,   IF_REAL,
                "Body-effect on drain-induced barrier lowering"),

IO("pvag",              B3SOI_MOD_PVAG,     IF_REAL,
                "Gate dependence of output resistance parameter"),

IO("shmod",             B3SOI_MOD_SHMOD,    IF_INTEGER,
                "Self heating mode selector"),
//IO("ddmod",             B3SOI_MOD_DDMOD,        IF_INTEGER,
//                        "Dynamic depletion mode selector"),
IO("tbox",              B3SOI_MOD_TBOX,     IF_REAL,
                "Back gate oxide thickness in meters"),
IO("tsi",               B3SOI_MOD_TSI,      IF_REAL,
                "Silicon-on-insulator thickness in meters"),
IO("xj",                B3SOI_MOD_XJ,       IF_REAL,
                "Junction Depth"),
IO("rth0",              B3SOI_MOD_RTH0,     IF_REAL,
                "Self-heating thermal resistance"),
IO("cth0",              B3SOI_MOD_CTH0,     IF_REAL,
                "Self-heating thermal capacitance"),
IO("ngidl",             B3SOI_MOD_NGIDL,    IF_REAL,
                "GIDL first parameter"),
IO("agidl",             B3SOI_MOD_AGIDL,    IF_REAL,
                "GIDL second parameter"),
IO("bgidl",             B3SOI_MOD_BGIDL,    IF_REAL,
                "GIDL third parameter"),
IO("ndiode",            B3SOI_MOD_NDIODE,   IF_REAL,
                "Diode non-ideality factor"),
IO("xbjt",              B3SOI_MOD_XBJT,     IF_REAL,
                "Temperature coefficient for Isbjt"),

IO("xdif",              B3SOI_MOD_XDIF,     IF_REAL,
                "Temperature coefficient for Isdif"),

IO("xrec",              B3SOI_MOD_XREC,     IF_REAL,
                "Temperature coefficient for Isrec"),
IO("xtun",              B3SOI_MOD_XTUN,     IF_REAL,
                "Temperature coefficient for Istun"),

IO("pbswg",             B3SOI_MOD_PBSWG,    IF_REAL,
                "Source/drain (gate side"),
IO("mjswg",             B3SOI_MOD_MJSWG,    IF_REAL,
                "Source/drain (gate side"),

IO("cjswg",             B3SOI_MOD_CJSWG,    IF_REAL,
                "Source/drain (gate side"),
IO("lint",              B3SOI_MOD_LINT,     IF_REAL,
                "Length reduction parameter"),
IO("ll",                B3SOI_MOD_LL,       IF_REAL,
                "Length reduction parameter"),
IO("llc",               B3SOI_MOD_LLC,      IF_REAL,
                "Length reduction parameter"),
IO("lln",               B3SOI_MOD_LLN,      IF_REAL,
                "Length reduction parameter"),
IO("lw",                B3SOI_MOD_LW,       IF_REAL,
                "Length reduction parameter"),
IO("lwc",               B3SOI_MOD_LWC,      IF_REAL,
                "Length reduction parameter"),
IO("lwn",               B3SOI_MOD_LWN,      IF_REAL,
                "Length reduction parameter"),
IO("lwl",               B3SOI_MOD_LWL,      IF_REAL,
                "Length reduction parameter"),
IO("lwlc",              B3SOI_MOD_LWLC,     IF_REAL,
                "Length reduction parameter"),

IO("wr",                B3SOI_MOD_WR,       IF_REAL,
                "Width dependence of rds"),
IO("wint",              B3SOI_MOD_WINT,     IF_REAL,
                "Width reduction parameter"),
IO("dwg",               B3SOI_MOD_DWG,      IF_REAL,
                "Width reduction parameter"),
IO("dwb",               B3SOI_MOD_DWB,      IF_REAL,
                "Width reduction parameter"),

IO("wl",                B3SOI_MOD_WL,       IF_REAL,
                "Width reduction parameter"),
IO("wlc",               B3SOI_MOD_WLC,      IF_REAL,
                "Width reduction parameter"),
IO("wln",               B3SOI_MOD_WLN,      IF_REAL,
                "Width reduction parameter"),
IO("ww",                B3SOI_MOD_WW,       IF_REAL,
                "Width reduction parameter"),
IO("wwc",               B3SOI_MOD_WWC,      IF_REAL,
                "Width reduction parameter"),
IO("wwn",               B3SOI_MOD_WWN,      IF_REAL,
                "Width reduction parameter"),
IO("wwl",               B3SOI_MOD_WWL,      IF_REAL,
                "Width reduction parameter"),
IO("wwlc",              B3SOI_MOD_WWLC,     IF_REAL,
                "Width reduction parameter"),

IO("b0",                B3SOI_MOD_B0,       IF_REAL,
                "Abulk narrow width parameter"),
IO("b1",                B3SOI_MOD_B1,       IF_REAL,
                "Abulk narrow width parameter"),

IO("cgsl",              B3SOI_MOD_CGSL,     IF_REAL,
                "New C-V model parameter"),
IO("cgdl",              B3SOI_MOD_CGDL,     IF_REAL,
                "New C-V model parameter"),
IO("ckappa",            B3SOI_MOD_CKAPPA,   IF_REAL,
                "New C-V model parameter"),
IO("cf",                B3SOI_MOD_CF,       IF_REAL,
                "Fringe capacitance parameter"),
IO("clc",               B3SOI_MOD_CLC,      IF_REAL,
                "Vdsat parameter for C-V model"),
IO("cle",               B3SOI_MOD_CLE,      IF_REAL,
                "Vdsat parameter for C-V model"),
IO("dwc",               B3SOI_MOD_DWC,      IF_REAL,
                "Delta W for C-V model"),
IO("dlc",               B3SOI_MOD_DLC,      IF_REAL,
                "Delta L for C-V model"),

IO("alpha0",            B3SOI_MOD_ALPHA0,   IF_REAL,
                "Substrate current model parameter"),

IO("noia",              B3SOI_MOD_NOIA,     IF_REAL,
                "Flicker noise parameter"),
IO("noib",              B3SOI_MOD_NOIB,     IF_REAL,
                "Flicker noise parameter"),
IO("noic",              B3SOI_MOD_NOIC,     IF_REAL,
                "Flicker noise parameter"),
IO("em",                B3SOI_MOD_EM,       IF_REAL,
                "Flicker noise parameter"),
IO("ef",                B3SOI_MOD_EF,       IF_REAL,
                "Flicker noise frequency exponent"),
IO("af",                B3SOI_MOD_AF,       IF_REAL,
                "Flicker noise exponent"),
IO("kf",                B3SOI_MOD_KF,       IF_REAL,
                "Flicker noise coefficient"),
IO("noif",              B3SOI_MOD_NOIF,     IF_REAL,
                "Floating body excess noise ideality factor"),

IO("k1w1",              B3SOI_MOD_K1W1,     IF_REAL,
                "First Body effect width dependent parameter"),
IO("k1w2",              B3SOI_MOD_K1W2,     IF_REAL,
                "Second Boby effect width dependent parameter"),
IO("ketas",             B3SOI_MOD_KETAS,    IF_REAL,
                "Surface potential adjustment for bulk charge effect"),
IO("dwbc",              B3SOI_MOD_DWBC,     IF_REAL,
                "Width offset for body contact isolation edge"),
IO("beta0",             B3SOI_MOD_BETA0,    IF_REAL,
                "First Vds dependent parameter of impact ionizition current"),
IO("beta1",             B3SOI_MOD_BETA1,    IF_REAL,
                "Second Vds dependent parameter of impact ionizition current"),
IO("beta2",             B3SOI_MOD_BETA2,    IF_REAL,
                "Third Vds dependent parameter of impact ionizition current"),
IO("vdsatii0",          B3SOI_MOD_VDSATII0, IF_REAL,
                "Nominal drain saturation voltage at threshold for impact ionizition current"),
IO("tii",               B3SOI_MOD_TII,      IF_REAL,
                "Temperature dependent parameter for impact ionizition"),
IO("lii",               B3SOI_MOD_LII,      IF_REAL,
                "Channel length dependent parameter at threshold for impact ionizition current"),
IO("sii0",              B3SOI_MOD_SII0,     IF_REAL,
                "First Vgs dependent parameter for impact ionizition current"),
IO("sii1",              B3SOI_MOD_SII1,     IF_REAL,
                "Second Vgs dependent parameter for impact ionizition current"),
IO("sii2",              B3SOI_MOD_SII2,     IF_REAL,
                "Third Vgs dependent parameter for impact ionizition current"),
IO("siid",              B3SOI_MOD_SIID,     IF_REAL,
                "Vds dependent parameter of drain saturation voltage for impact ionizition current"),
IO("fbjtii",            B3SOI_MOD_FBJTII,   IF_REAL,
                "Fraction of bipolar current affecting the impact ionization"),
IO("esatii",            B3SOI_MOD_ESATII,   IF_REAL,
                "Saturation electric field for impact ionization"),
IO("ntun",              B3SOI_MOD_NTUN,     IF_REAL,
                "Reverse tunneling non-ideality factor"),
IO("nrecf0",            B3SOI_MOD_NRECF0,   IF_REAL,
                "Recombination non-ideality factor at forward bias"),
IO("nrecr0",            B3SOI_MOD_NRECR0,   IF_REAL,
                "Recombination non-ideality factor at reversed bias"),
IO("isbjt",             B3SOI_MOD_ISBJT,    IF_REAL,
                "BJT injection saturation current"),
IO("isdif",             B3SOI_MOD_ISDIF,    IF_REAL,
                "Body to source/drain injection saturation current"),
IO("isrec",             B3SOI_MOD_ISREC,    IF_REAL,
                "Recombination in depletion saturation current"),
IO("istun",             B3SOI_MOD_ISTUN,    IF_REAL,
                "Reverse tunneling saturation current"),
IO("ln",                B3SOI_MOD_LN,       IF_REAL,
                "Electron/hole diffusion length"),
IO("vrec0",             B3SOI_MOD_VREC0,    IF_REAL,
                "Voltage dependent parameter for recombination current"),
IO("vtun0",             B3SOI_MOD_VTUN0,    IF_REAL,
                "Voltage dependent parameter for tunneling current"),
IO("nbjt",              B3SOI_MOD_NBJT,     IF_REAL,
                "Power coefficient of channel length dependency for bipolar current"),
IO("lbjt0",             B3SOI_MOD_LBJT0,    IF_REAL,
                "Refferenc channel length for bipolar cuurent"),
IO("ldif0",             B3SOI_MOD_LDIF0,    IF_REAL,
                "Channel-length dependency coefficient of diffusion cap"),
IO("vabjt",             B3SOI_MOD_VABJT,    IF_REAL,
                "Early voltage for bipolar current"),
IO("aely",              B3SOI_MOD_AELY,     IF_REAL,
                "Channel length dependency of early voltage for bipolar cuurent"),
IO("ahli",              B3SOI_MOD_AHLI,     IF_REAL,
                "High level injection parameter for bipolar current"),
IO("rbody",             B3SOI_MOD_RBODY,    IF_REAL,
                "Intrinsic body contact sheet resistance"),
IO("rbsh",              B3SOI_MOD_RBSH,     IF_REAL,
                "Extrinsic body contact sheet resistance"),
IO("cgeo",              B3SOI_MOD_CGEO,     IF_REAL,
                "Gate substrate overlap capacitance per unit channel length"),
IO("tt",                B3SOI_MOD_TT,       IF_REAL,
                "Diffusion capacitance transit time coefficient"),
IO("ndif",              B3SOI_MOD_NDIF,     IF_REAL,
                "Power coefficient of channel length dependency for diffusion capacitance"),
IO("vsdfb",             B3SOI_MOD_VSDFB,    IF_REAL,
                "Source/drain bottom diffusion capacitance flatband voltage"),
IO("vsdth",             B3SOI_MOD_VSDTH,    IF_REAL,
                "Source/drain bottom diffusion capacitance threshold voltage"),
IO("csdmin",            B3SOI_MOD_CSDMIN,   IF_REAL,
                "Source/drain bottom diffusion minimum capacitance"),
IO("asd",               B3SOI_MOD_ASD,      IF_REAL,
                "Source/drain bottom diffusion smoothing parameter"),
IO("csdesw",            B3SOI_MOD_CSDESW,   IF_REAL,
                "Source/drain sidewall fringing capacitance per unit length"),
IO("ntrecf",            B3SOI_MOD_NTRECF,   IF_REAL,
                "Temperature coefficient for Nrecf"),
IO("ntrecr",            B3SOI_MOD_NTRECR,   IF_REAL,
                "Temperature coefficient for Nrecr"),
IO("dlcb",              B3SOI_MOD_DLCB,     IF_REAL,
                "Length offset fitting parameter for body charge"),
IO("fbody",             B3SOI_MOD_FBODY,    IF_REAL,
                "Scaling factor for body charge"),
IO("tcjswg",            B3SOI_MOD_TCJSWG,   IF_REAL,
                "Temperature coefficient of Cjswg"),
IO("tpbswg",            B3SOI_MOD_TPBSWG,   IF_REAL,
                "Temperature coefficient of Pbswg"),
IO("acde",              B3SOI_MOD_ACDE,     IF_REAL,
                "Exponential coefficient for charge thickness in capMod=3 for accumulation and depletion regions"),
IO("moin",              B3SOI_MOD_MOIN,     IF_REAL,
                "Coefficient for the gate-bias dependent surface potential"),
IO("delvt",             B3SOI_MOD_DELVT,    IF_REAL,
                "Threshold voltage adjust for CV"),
IO("kb1",               B3SOI_MOD_KB1,      IF_REAL,
                "Scaling factor for backgate charge"),
IO("dlbg",              B3SOI_MOD_DLBG,     IF_REAL,
                "Length offset fitting parameter for backgate charge"),

IO("igbmod",            B3SOI_MOD_IGBMOD,   IF_INTEGER,
                "Gate-body tunneling current model selector"),
IO("igcmod",            B3SOI_MOD_IGCMOD,   IF_INTEGER,
                "Gate-channel tunneling current model selector"),
IO("toxqm",             B3SOI_MOD_TOXQM,    IF_REAL,
                "Effective oxide thickness considering quantum effect"),
IO("wth0",              B3SOI_MOD_WTH0,     IF_REAL,
                "Minimum width for thermal resistance calculation"),
IO("rhalo",             B3SOI_MOD_RHALO,    IF_REAL,
                "Body halo sheet resistance"),
IO("ntox",              B3SOI_MOD_NTOX,     IF_REAL,
                "Power term of gate current"),
IO("toxref",            B3SOI_MOD_TOXREF,   IF_REAL,
                "Target oxide thickness"),
IO("ebg",               B3SOI_MOD_EBG,      IF_REAL,
                "Effective bandgap in gate current calcula."),
IO("vevb",              B3SOI_MOD_VEVB,     IF_REAL,
                "Vaux parameter for valence-band electron tunneling"),
IO("alphagb1",          B3SOI_MOD_ALPHAGB1, IF_REAL,
                "First Vox dependent parameter for gate curent in inversion"),
IO("betagb1",           B3SOI_MOD_BETAGB1,  IF_REAL,
                "Second Vox dependent parameter for gate currnt in inversion"),
IO("vgb1",              B3SOI_MOD_VGB1,     IF_REAL,
                "Third Vox dependent parameter for gate current in inversion"),
IO("vecb",              B3SOI_MOD_VECB,     IF_REAL,
                "Vaux parameter for conduction-band electron tunneling"),
IO("alphagb2",          B3SOI_MOD_ALPHAGB2, IF_REAL,
                "First Vox dependent parameter for gate current in accumulation"),
IO("betagb2",           B3SOI_MOD_BETAGB2,  IF_REAL,
                "Second Vox dependent parameter for gate current in accumulation"),
IO("vgb2",              B3SOI_MOD_VGB2,     IF_REAL,
                "Third Vox dependent parameter for gate current in accumulation"),
IO("voxh",              B3SOI_MOD_VOXH,     IF_REAL,
                "The limit of Vox in gate current calculation"),
IO("deltavox",          B3SOI_MOD_DELTAVOX, IF_REAL,
                "The smoothing parameter in the Vox smoothing function"),

IO("aigc",              B3SOI_MOD_AIGC,     IF_REAL,
                "Parameter for Igc"),
IO("bigc",              B3SOI_MOD_BIGC,     IF_REAL,
                "Parameter for Igc"),
IO("cigc",              B3SOI_MOD_CIGC,     IF_REAL,
                "Parameter for Igc"),
IO("aigsd",             B3SOI_MOD_AIGSD,    IF_REAL,
                "Parameter for Igs,d"),
IO("bigsd",             B3SOI_MOD_BIGSD,    IF_REAL,
                "Parameter for Igs,d"),
IO("cigsd",             B3SOI_MOD_CIGSD,    IF_REAL,
                "Parameter for Igs,d"),
IO("nigc",              B3SOI_MOD_NIGC,     IF_REAL,
                "Parameter for Igc slope"),
IO("pigcd",             B3SOI_MOD_PIGCD,    IF_REAL,
                "Parameter for Igc partition"),
IO("poxedge",           B3SOI_MOD_POXEDGE,  IF_REAL,
                "Factor for the gate edge Tox"),
IO("dlcig",             B3SOI_MOD_DLCIG,    IF_REAL,
                "Delta L for Ig model"),

IO("soimod",            B3SOI_MOD_SOIMOD,   IF_REAL,
                "Model selector for SOI technology"),
IO("vbsa",              B3SOI_MOD_VBSA,     IF_REAL,
                "Vbs0t offset voltage"),
IO("nofffd",            B3SOI_MOD_NOFFFD,   IF_REAL,
                "Smoothing parameter in FD module"),
IO("vofffd",            B3SOI_MOD_VOFFFD,   IF_REAL,
                "Smoothing parameter in FD module"),
IO("k1b",               B3SOI_MOD_K1B,      IF_REAL,
                "First backgate body effect parameter"),
IO("k2b",               B3SOI_MOD_K2B,      IF_REAL,
                "Second backgate body effect parameter for short channel effect"),
IO("dk2b",              B3SOI_MOD_DK2B,     IF_REAL,
                "Third backgate body effect parameter for short channel effect"),
IO("dvbd0",             B3SOI_MOD_DVBD0,    IF_REAL,
                "First short-channel effect parameter in FD module"),
IO("dvbd1",             B3SOI_MOD_DVBD1,    IF_REAL,
                "Second short-channel effect parameter in FD module"),
IO("moinfd",            B3SOI_MOD_MOINFD,   IF_REAL,
                "Coefficient for the gate-bias dependent surface potential in FD"),

IO("laigc",             B3SOI_MOD_LAIGC,    IF_REAL,
                "Length dependence of aigc"),
IO("lbigc",             B3SOI_MOD_LBIGC,    IF_REAL,
                "Length dependence of bigc"),
IO("lcigc",             B3SOI_MOD_LCIGC,    IF_REAL,
                "Length dependence of cigc"),
IO("laigsd",            B3SOI_MOD_LAIGSD,   IF_REAL,
                "Length dependence of aigsd"),
IO("lbigsd",            B3SOI_MOD_LBIGSD,   IF_REAL,
                "Length dependence of bigsd"),
IO("lcigsd",            B3SOI_MOD_LCIGSD,   IF_REAL,
                "Length dependence of cigsd"),
IO("lnigc",             B3SOI_MOD_LNIGC,    IF_REAL,
                "Length dependence of nigc"),
IO("lpigcd",            B3SOI_MOD_LPIGCD,   IF_REAL,
                "Length dependence for pigcd"),
IO("lpoxedge",          B3SOI_MOD_LPOXEDGE, IF_REAL,
                "Length dependence for poxedge"),

IO("lnch",              B3SOI_MOD_LNPEAK,   IF_REAL,
                "Length dependence of nch"),
IO("lnsub",             B3SOI_MOD_LNSUB,    IF_REAL,
                "Length dependence of nsub"),
IO("lngate",            B3SOI_MOD_LNGATE,   IF_REAL,
                "Length dependence of ngate"),
IO("lvth0",             B3SOI_MOD_LVTH0,    IF_REAL,
                "Length dependence of vto"),
IO("lk1",               B3SOI_MOD_LK1,      IF_REAL,
                "Length dependence of k1"),
IO("lk1w1",             B3SOI_MOD_LK1W1,    IF_REAL,
                "Length dependence of k1w1"),
IO("lk1w2",             B3SOI_MOD_LK1W2,    IF_REAL,
                "Length dependence of k1w2"),
IO("lk2",               B3SOI_MOD_LK2,      IF_REAL,
                "Length dependence of k2"),
IO("lk3",               B3SOI_MOD_LK3,      IF_REAL,
                "Length dependence of k3"),
IO("lk3b",              B3SOI_MOD_LK3B,     IF_REAL,
                "Length dependence of k3b"),
IO("lkb1",              B3SOI_MOD_LKB1,     IF_REAL,
                "Length dependence of kb1"),
IO("lw0",               B3SOI_MOD_LW0,      IF_REAL,
                "Length dependence of w0"),
IO("lnlx",              B3SOI_MOD_LNLX,     IF_REAL,
                "Length dependence of nlx"),
IO("ldvt0",             B3SOI_MOD_LDVT0,    IF_REAL,
                "Length dependence of dvt0"),
IO("ldvt1",             B3SOI_MOD_LDVT1,    IF_REAL,
                "Length dependence of dvt1"),
IO("ldvt2",             B3SOI_MOD_LDVT2,    IF_REAL,
                "Length dependence of dvt2"),
IO("ldvt0w",            B3SOI_MOD_LDVT0W,   IF_REAL,
                "Length dependence of dvt0w"),
IO("ldvt1w",            B3SOI_MOD_LDVT1W,   IF_REAL,
                "Length dependence of dvt1w"),
IO("ldvt2w",            B3SOI_MOD_LDVT2W,   IF_REAL,
                "Length dependence of dvt2w"),
IO("lu0",               B3SOI_MOD_LU0,      IF_REAL,
                "Length dependence of u0"),
IO("lua",               B3SOI_MOD_LUA,      IF_REAL,
                "Length dependence of ua"),
IO("lub",               B3SOI_MOD_LUB,      IF_REAL,
                "Length dependence of ub"),
IO("luc",               B3SOI_MOD_LUC,      IF_REAL,
                "Length dependence of uc"),
IO("lvsat",             B3SOI_MOD_LVSAT,    IF_REAL,
                "Length dependence of vsat"),
IO("la0",               B3SOI_MOD_LA0,      IF_REAL,
                "Length dependence of a0"),
IO("lags",              B3SOI_MOD_LAGS,     IF_REAL,
                "Length dependence of ags"),
IO("lb0",               B3SOI_MOD_LB0,      IF_REAL,
                "Length dependence of b0"),
IO("lb1",               B3SOI_MOD_LB1,      IF_REAL,
                "Length dependence of b1"),
IO("lketa",             B3SOI_MOD_LKETA,    IF_REAL,
                "Length dependence of keta"),
IO("lketas",            B3SOI_MOD_LKETAS,   IF_REAL,
                "Length dependence of ketas"),
IO("la1",               B3SOI_MOD_LA1,      IF_REAL,
                "Length dependence of a1"),
IO("la2",               B3SOI_MOD_LA2,      IF_REAL,
                "Length dependence of a2"),
IO("lrdsw",             B3SOI_MOD_LRDSW,    IF_REAL,
                "Length dependence of rdsw"),
IO("lprwb",             B3SOI_MOD_LPRWB,    IF_REAL,
                "Length dependence of prwb"),
IO("lprwg",             B3SOI_MOD_LPRWG,    IF_REAL,
                "Length dependence of prwg"),
IO("lwr",               B3SOI_MOD_LWR,      IF_REAL,
                "Length dependence of wr"),
IO("lnfactor",          B3SOI_MOD_LNFACTOR, IF_REAL,
                "Length dependence of nfactor"),
IO("ldwg",              B3SOI_MOD_LDWG,     IF_REAL,
                "Length dependence of dwg"),
IO("ldwb",              B3SOI_MOD_LDWB,     IF_REAL,
                "Length dependence of dwb"),
IO("lvoff",             B3SOI_MOD_LVOFF,    IF_REAL,
                "Length dependence of voff"),
IO("leta0",             B3SOI_MOD_LETA0,    IF_REAL,
                "Length dependence of eta0"),
IO("letab",             B3SOI_MOD_LETAB,    IF_REAL,
                "Length dependence of etab"),
IO("ldsub",             B3SOI_MOD_LDSUB,    IF_REAL,
                "Length dependence of dsub"),
IO("lcit",              B3SOI_MOD_LCIT,     IF_REAL,
                "Length dependence of cit"),
IO("lcdsc",             B3SOI_MOD_LCDSC,    IF_REAL,
                "Length dependence of cdsc"),
IO("lcdscb",            B3SOI_MOD_LCDSCB,   IF_REAL,
                "Length dependence of cdscb"),
IO("lcdscd",            B3SOI_MOD_LCDSCD,   IF_REAL,
                "Length dependence of cdscd"),
IO("lpclm",             B3SOI_MOD_LPCLM,    IF_REAL,
                "Length dependence of pclm"),
IO("lpdiblc1",          B3SOI_MOD_LPDIBL1,  IF_REAL,
                "Length dependence of pdiblc1"),
IO("lpdiblc2",          B3SOI_MOD_LPDIBL2,  IF_REAL,
                "Length dependence of pdiblc2"),
IO("lpdiblcb",          B3SOI_MOD_LPDIBLB,  IF_REAL,
                "Length dependence of pdiblcb"),
IO("ldrout",            B3SOI_MOD_LDROUT,   IF_REAL,
                "Length dependence of drout"),
IO("lpvag",             B3SOI_MOD_LPVAG,    IF_REAL,
                "Length dependence of pvag"),
IO("ldelta",            B3SOI_MOD_LDELTA,   IF_REAL,
                "Length dependence of delta"),
IO("lalpha0",           B3SOI_MOD_LALPHA0,  IF_REAL,
                "Length dependence of alpha0"),
IO("lfbjtii",           B3SOI_MOD_LFBJTII,  IF_REAL,
                "Length dependence of fbjtii"),
IO("lbeta0",            B3SOI_MOD_LBETA0,   IF_REAL,
                "Length dependence of beta0"),
IO("lbeta1",            B3SOI_MOD_LBETA1,   IF_REAL,
                "Length dependence of beta1"),
IO("lbeta2",            B3SOI_MOD_LBETA2,   IF_REAL,
                "Length dependence of beta2"),
IO("lvdsatii0",         B3SOI_MOD_LVDSATII0,IF_REAL,
                "Length dependence of vdsatii0"),
IO("llii",              B3SOI_MOD_LLII,     IF_REAL,
                "Length dependence of lii"),
IO("lesatii",           B3SOI_MOD_LESATII,  IF_REAL,
                "Length dependence of esatii"),
IO("lsii0",             B3SOI_MOD_LSII0,    IF_REAL,
                "Length dependence of sii0"),
IO("lsii1",             B3SOI_MOD_LSII1,    IF_REAL,
                "Length dependence of sii1"),
IO("lsii2",             B3SOI_MOD_LSII2,    IF_REAL,
                "Length dependence of sii2"),
IO("lsiid",             B3SOI_MOD_LSIID,    IF_REAL,
                "Length dependence of siid"),
IO("lagidl",            B3SOI_MOD_LAGIDL,   IF_REAL,
                "Length dependence of agidl"),
IO("lbgidl",            B3SOI_MOD_LBGIDL,   IF_REAL,
                "Length dependence of bgidl"),
IO("lngidl",            B3SOI_MOD_LNGIDL,   IF_REAL,
                "Length dependence of ngidl"),
IO("lntun",             B3SOI_MOD_LNTUN,    IF_REAL,
                "Length dependence of ntun"),
IO("lndiode",           B3SOI_MOD_LNDIODE,  IF_REAL,
                "Length dependence of ndiode"),
IO("lnrecf0",           B3SOI_MOD_LNRECF0,  IF_REAL,
                "Length dependence of nrecf0"),
IO("lnrecr0",           B3SOI_MOD_LNRECR0,  IF_REAL,
                "Length dependence of nrecr0"),
IO("lisbjt",            B3SOI_MOD_LISBJT,   IF_REAL,
                "Length dependence of isbjt"),
IO("lisdif",            B3SOI_MOD_LISDIF,   IF_REAL,
                "Length dependence of isdif"),
IO("lisrec",            B3SOI_MOD_LISREC,   IF_REAL,
                "Length dependence of isrec"),
IO("listun",            B3SOI_MOD_LISTUN,   IF_REAL,
                "Length dependence of istun"),
IO("lvrec0",            B3SOI_MOD_LVREC0,   IF_REAL,
                "Length dependence of vrec0"),
IO("lvtun0",            B3SOI_MOD_LVTUN0,   IF_REAL,
                "Length dependence of vtun0"),
IO("lnbjt",             B3SOI_MOD_LNBJT,    IF_REAL,
                "Length dependence of nbjt"),
IO("llbjt0",            B3SOI_MOD_LLBJT0,   IF_REAL,
                "Length dependence of lbjt0"),
IO("lvabjt",            B3SOI_MOD_LVABJT,   IF_REAL,
                "Length dependence of vabjt"),
IO("laely",             B3SOI_MOD_LAELY,    IF_REAL,
                "Length dependence of aely"),
IO("lahli",             B3SOI_MOD_LAHLI,    IF_REAL,
                "Length dependence of ahli"),
IO("lvsdfb",            B3SOI_MOD_LVSDFB,   IF_REAL,
                "Length dependence of vsdfb"),
IO("lvsdth",            B3SOI_MOD_LVSDTH,   IF_REAL,
                "Length dependence of vsdth"),
IO("ldelvt",            B3SOI_MOD_LDELVT,   IF_REAL,
                "Length dependence of delvt"),
IO("lacde",             B3SOI_MOD_LACDE,    IF_REAL,
                "Length dependence of acde"),
IO("lmoin",             B3SOI_MOD_LMOIN,    IF_REAL,
                "Length dependence of amoin"),

IO("waigc",             B3SOI_MOD_WAIGC,    IF_REAL,
                "Width dependence of aigc"),
IO("wbigc",             B3SOI_MOD_WBIGC,    IF_REAL,
                "Width dependence of bigc"),
IO("wcigc",             B3SOI_MOD_WCIGC,    IF_REAL,
                "Width dependence of cigc"),
IO("waigsd",            B3SOI_MOD_WAIGSD,   IF_REAL,
                "Width dependence of aigsd"),
IO("wbigsd",            B3SOI_MOD_WBIGSD,   IF_REAL,
                "Width dependence of bigsd"),
IO("wcigsd",            B3SOI_MOD_WCIGSD,   IF_REAL,
                "Width dependence of cigsd"),
IO("wnigc",             B3SOI_MOD_WNIGC,    IF_REAL,
                "Width dependence of nigc"),
IO("wpigcd",            B3SOI_MOD_WPIGCD,   IF_REAL,
                "Width dependence for pigcd"),
IO("wpoxedge",          B3SOI_MOD_WPOXEDGE, IF_REAL,
                "Width dependence for poxedge"),

IO("wnch",              B3SOI_MOD_WNPEAK,   IF_REAL,
                "Width dependence of nch"),
IO("wnsub",             B3SOI_MOD_WNSUB,    IF_REAL,
                "Width dependence of nsub"),
IO("wngate",            B3SOI_MOD_WNGATE,   IF_REAL,
                "Width dependence of ngate"),
IO("wvth0",             B3SOI_MOD_WVTH0,    IF_REAL,
                "Width dependence of vto"),
IO("wk1",               B3SOI_MOD_WK1,      IF_REAL,
                "Width dependence of k1"),
IO("wk1w1",             B3SOI_MOD_WK1W1,    IF_REAL,
                "Width dependence of k1w1"),
IO("wk1w2",             B3SOI_MOD_WK1W2,    IF_REAL,
                "Width dependence of k1w2"),
IO("wk2",               B3SOI_MOD_WK2,      IF_REAL,
                "Width dependence of k2"),
IO("wk3",               B3SOI_MOD_WK3,      IF_REAL,
                "Width dependence of k3"),
IO("wk3b",              B3SOI_MOD_WK3B,     IF_REAL,
                "Width dependence of k3b"),
IO("wkb1",              B3SOI_MOD_WKB1,     IF_REAL,
                "Width dependence of kb1"),
IO("ww0",               B3SOI_MOD_WW0,      IF_REAL,
                "Width dependence of w0"),
IO("wnlx",              B3SOI_MOD_WNLX,     IF_REAL,
                "Width dependence of nlx"),
IO("wdvt0",             B3SOI_MOD_WDVT0,    IF_REAL,
                "Width dependence of dvt0"),
IO("wdvt1",             B3SOI_MOD_WDVT1,    IF_REAL,
                "Width dependence of dvt1"),
IO("wdvt2",             B3SOI_MOD_WDVT2,    IF_REAL,
                "Width dependence of dvt2"),
IO("wdvt0w",            B3SOI_MOD_WDVT0W,   IF_REAL,
                "Width dependence of dvt0w"),
IO("wdvt1w",            B3SOI_MOD_WDVT1W,   IF_REAL,
                "Width dependence of dvt1w"),
IO("wdvt2w",            B3SOI_MOD_WDVT2W,   IF_REAL,
                "Width dependence of dvt2w"),
IO("wu0",               B3SOI_MOD_WU0,      IF_REAL,
                "Width dependence of u0"),
IO("wua",               B3SOI_MOD_WUA,      IF_REAL,
                "Width dependence of ua"),
IO("wub",               B3SOI_MOD_WUB,      IF_REAL,
                "Width dependence of ub"),
IO("wuc",               B3SOI_MOD_WUC,      IF_REAL,
                "Width dependence of uc"),
IO("wvsat",             B3SOI_MOD_WVSAT,    IF_REAL,
                "Width dependence of vsat"),
IO("wa0",               B3SOI_MOD_WA0,      IF_REAL,
                "Width dependence of a0"),
IO("wags",              B3SOI_MOD_WAGS,     IF_REAL,
                "Width dependence of ags"),
IO("wb0",               B3SOI_MOD_WB0,      IF_REAL,
                "Width dependence of b0"),
IO("wb1",               B3SOI_MOD_WB1,      IF_REAL,
                "Width dependence of b1"),
IO("wketa",             B3SOI_MOD_WKETA,    IF_REAL,
                "Width dependence of keta"),
IO("wketas",            B3SOI_MOD_WKETAS,   IF_REAL,
                "Width dependence of ketas"),
IO("wa1",               B3SOI_MOD_WA1,      IF_REAL,
                "Width dependence of a1"),
IO("wa2",               B3SOI_MOD_WA2,      IF_REAL,
                "Width dependence of a2"),
IO("wrdsw",             B3SOI_MOD_WRDSW,    IF_REAL,
                "Width dependence of rdsw"),
IO("wprwb",             B3SOI_MOD_WPRWB,    IF_REAL,
                "Width dependence of prwb"),
IO("wprwg",             B3SOI_MOD_WPRWG,    IF_REAL,
                "Width dependence of prwg"),
IO("wwr",               B3SOI_MOD_WWR,      IF_REAL,
                "Width dependence of wr"),
IO("wnfactor",          B3SOI_MOD_WNFACTOR, IF_REAL,
                "Width dependence of nfactor"),
IO("wdwg",              B3SOI_MOD_WDWG,     IF_REAL,
                "Width dependence of dwg"),
IO("wdwb",              B3SOI_MOD_WDWB,     IF_REAL,
                "Width dependence of dwb"),
IO("wvoff",             B3SOI_MOD_WVOFF,    IF_REAL,
                "Width dependence of voff"),
IO("weta0",             B3SOI_MOD_WETA0,    IF_REAL,
                "Width dependence of eta0"),
IO("wetab",             B3SOI_MOD_WETAB,    IF_REAL,
                "Width dependence of etab"),
IO("wdsub",             B3SOI_MOD_WDSUB,    IF_REAL,
                "Width dependence of dsub"),
IO("wcit",              B3SOI_MOD_WCIT,     IF_REAL,
                "Width dependence of cit"),
IO("wcdsc",             B3SOI_MOD_WCDSC,    IF_REAL,
                "Width dependence of cdsc"),
IO("wcdscb",            B3SOI_MOD_WCDSCB,   IF_REAL,
                "Width dependence of cdscb"),
IO("wcdscd",            B3SOI_MOD_WCDSCD,   IF_REAL,
                "Width dependence of cdscd"),
IO("wpclm",             B3SOI_MOD_WPCLM,    IF_REAL,
                "Width dependence of pclm"),
IO("wpdiblc1",          B3SOI_MOD_WPDIBL1,  IF_REAL,
                "Width dependence of pdiblc1"),
IO("wpdiblc2",          B3SOI_MOD_WPDIBL2,  IF_REAL,
                "Width dependence of pdiblc2"),
IO("wpdiblcb",          B3SOI_MOD_WPDIBLB,  IF_REAL,
                "Width dependence of pdiblcb"),
IO("wdrout",            B3SOI_MOD_WDROUT,   IF_REAL,
                "Width dependence of drout"),
IO("wpvag",             B3SOI_MOD_WPVAG,    IF_REAL,
                "Width dependence of pvag"),
IO("wdelta",            B3SOI_MOD_WDELTA,   IF_REAL,
                "Width dependence of delta"),
IO("walpha0",           B3SOI_MOD_WALPHA0,  IF_REAL,
                "Width dependence of alpha0"),
IO("wfbjtii",           B3SOI_MOD_WFBJTII,  IF_REAL,
                "Width dependence of fbjtii"),
IO("wbeta0",            B3SOI_MOD_WBETA0,   IF_REAL,
                "Width dependence of beta0"),
IO("wbeta1",            B3SOI_MOD_WBETA1,   IF_REAL,
                "Width dependence of beta1"),
IO("wbeta2",            B3SOI_MOD_WBETA2,   IF_REAL,
                "Width dependence of beta2"),
IO("wvdsatii0",         B3SOI_MOD_WVDSATII0,IF_REAL,
                "Width dependence of vdsatii0"),
IO("wlii",              B3SOI_MOD_WLII,     IF_REAL,
                "Width dependence of lii"),
IO("wesatii",           B3SOI_MOD_WESATII,  IF_REAL,
                "Width dependence of esatii"),
IO("wsii0",             B3SOI_MOD_WSII0,    IF_REAL,
                "Width dependence of sii0"),
IO("wsii1",             B3SOI_MOD_WSII1,    IF_REAL,
                "Width dependence of sii1"),
IO("wsii2",             B3SOI_MOD_WSII2,    IF_REAL,
                "Width dependence of sii2"),
IO("wsiid",             B3SOI_MOD_WSIID,    IF_REAL,
                "Width dependence of siid"),
IO("wagidl",            B3SOI_MOD_WAGIDL,   IF_REAL,
                "Width dependence of agidl"),
IO("wbgidl",            B3SOI_MOD_WBGIDL,   IF_REAL,
                "Width dependence of bgidl"),
IO("wngidl",            B3SOI_MOD_WNGIDL,   IF_REAL,
                "Width dependence of ngidl"),
IO("wntun",             B3SOI_MOD_WNTUN,    IF_REAL,
                "Width dependence of ntun"),
IO("wndiode",           B3SOI_MOD_WNDIODE,  IF_REAL,
                "Width dependence of ndiode"),
IO("wnrecf0",           B3SOI_MOD_WNRECF0,  IF_REAL,
                "Width dependence of nrecf0"),
IO("wnrecr0",           B3SOI_MOD_WNRECR0,  IF_REAL,
                "Width dependence of nrecr0"),
IO("wisbjt",            B3SOI_MOD_WISBJT,   IF_REAL,
                "Width dependence of isbjt"),
IO("wisdif",            B3SOI_MOD_WISDIF,   IF_REAL,
                "Width dependence of isdif"),
IO("wisrec",            B3SOI_MOD_WISREC,   IF_REAL,
                "Width dependence of isrec"),
IO("wistun",            B3SOI_MOD_WISTUN,   IF_REAL,
                "Width dependence of istun"),
IO("wvrec0",            B3SOI_MOD_WVREC0,   IF_REAL,
                "Width dependence of vrec0"),
IO("wvtun0",            B3SOI_MOD_WVTUN0,   IF_REAL,
                "Width dependence of vtun0"),
IO("wnbjt",             B3SOI_MOD_WNBJT,    IF_REAL,
                "Width dependence of nbjt"),
IO("wlbjt0",            B3SOI_MOD_WLBJT0,   IF_REAL,
                "Width dependence of lbjt0"),
IO("wvabjt",            B3SOI_MOD_WVABJT,   IF_REAL,
                "Width dependence of vabjt"),
IO("waely",             B3SOI_MOD_WAELY,    IF_REAL,
                "Width dependence of aely"),
IO("wahli",             B3SOI_MOD_WAHLI,    IF_REAL,
                "Width dependence of ahli"),
IO("wvsdfb",            B3SOI_MOD_WVSDFB,   IF_REAL,
                "Width dependence of vsdfb"),
IO("wvsdth",            B3SOI_MOD_WVSDTH,   IF_REAL,
                "Width dependence of vsdth"),
IO("wdelvt",            B3SOI_MOD_WDELVT,   IF_REAL,
                "Width dependence of delvt"),
IO("wacde",             B3SOI_MOD_WACDE,    IF_REAL,
                "Width dependence of acde"),
IO("wmoin",             B3SOI_MOD_WMOIN,    IF_REAL,
                "Width dependence of amoin"),

IO("paigc",             B3SOI_MOD_PAIGC,    IF_REAL,
                "Cross-term dependence of aigc"),
IO("pbigc",             B3SOI_MOD_PBIGC,    IF_REAL,
                "Cross-term dependence of bigc"),
IO("pcigc",             B3SOI_MOD_PCIGC,    IF_REAL,
                "Cross-term dependence of cigc"),
IO("paigsd",            B3SOI_MOD_PAIGSD,   IF_REAL,
                "Cross-term dependence of aigsd"),
IO("pbigsd",            B3SOI_MOD_PBIGSD,   IF_REAL,
                "Cross-term dependence of bigsd"),
IO("pcigsd",            B3SOI_MOD_PCIGSD,   IF_REAL,
                "Cross-term dependence of cigsd"),
IO("pnigc",             B3SOI_MOD_PNIGC,    IF_REAL,
                "Cross-term dependence of nigc"),
IO("ppigcd",            B3SOI_MOD_PPIGCD,   IF_REAL,
                "Cross-term dependence for pigcd"),
IO("ppoxedge",          B3SOI_MOD_PPOXEDGE, IF_REAL,
                "Cross-term dependence for poxedge"),

IO("pnch",              B3SOI_MOD_PNPEAK,   IF_REAL,
                "Cross-term dependence of nch"),
IO("pnsub",             B3SOI_MOD_PNSUB,    IF_REAL,
                "Cross-term dependence of nsub"),
IO("pngate",            B3SOI_MOD_PNGATE,   IF_REAL,
                "Cross-term dependence of ngate"),
IO("pvth0",             B3SOI_MOD_PVTH0,    IF_REAL,
                "Cross-term dependence of vto"),
IO("pk1",               B3SOI_MOD_PK1,      IF_REAL,
                "Cross-term dependence of k1"),
IO("pk1w1",             B3SOI_MOD_PK1W1,    IF_REAL,
                "Cross-term dependence of k1w1"),
IO("pk1w2",             B3SOI_MOD_PK1W2,    IF_REAL,
                "Cross-term dependence of k1w2"),
IO("pk2",               B3SOI_MOD_PK2,      IF_REAL,
                "Cross-term dependence of k2"),
IO("pk3",               B3SOI_MOD_PK3,      IF_REAL,
                "Cross-term dependence of k3"),
IO("pk3b",              B3SOI_MOD_PK3B,     IF_REAL,
                "Cross-term dependence of k3b"),
IO("pkb1",              B3SOI_MOD_PKB1,     IF_REAL,
                "Cross-term dependence of kb1"),
IO("pw0",               B3SOI_MOD_PW0,      IF_REAL,
                "Cross-term dependence of w0"),
IO("pnlx",              B3SOI_MOD_PNLX,     IF_REAL,
                "Cross-term dependence of nlx"),
IO("pdvt0",             B3SOI_MOD_PDVT0,    IF_REAL,
                "Cross-term dependence of dvt0"),
IO("pdvt1",             B3SOI_MOD_PDVT1,    IF_REAL,
                "Cross-term dependence of dvt1"),
IO("pdvt2",             B3SOI_MOD_PDVT2,    IF_REAL,
                "Cross-term dependence of dvt2"),
IO("pdvt0w",            B3SOI_MOD_PDVT0W,   IF_REAL,
                "Cross-term dependence of dvt0w"),
IO("pdvt1w",            B3SOI_MOD_PDVT1W,   IF_REAL,
                "Cross-term dependence of dvt1w"),
IO("pdvt2w",            B3SOI_MOD_PDVT2W,   IF_REAL,
                "Cross-term dependence of dvt2w"),
IO("pu0",               B3SOI_MOD_PU0,      IF_REAL,
                "Cross-term dependence of u0"),
IO("pua",               B3SOI_MOD_PUA,      IF_REAL,
                "Cross-term dependence of ua"),
IO("pub",               B3SOI_MOD_PUB,      IF_REAL,
                "Cross-term dependence of ub"),
IO("puc",               B3SOI_MOD_PUC,      IF_REAL,
                "Cross-term dependence of uc"),
IO("pvsat",             B3SOI_MOD_PVSAT,    IF_REAL,
                "Cross-term dependence of vsat"),
IO("pa0",               B3SOI_MOD_PA0,      IF_REAL,
                "Cross-term dependence of a0"),
IO("pags",              B3SOI_MOD_PAGS,     IF_REAL,
                "Cross-term dependence of ags"),
IO("pb0",               B3SOI_MOD_PB0,      IF_REAL,
                "Cross-term dependence of b0"),
IO("pb1",               B3SOI_MOD_PB1,      IF_REAL,
                "Cross-term dependence of b1"),
IO("pketa",             B3SOI_MOD_PKETA,    IF_REAL,
                "Cross-term dependence of keta"),
IO("pketas",            B3SOI_MOD_PKETAS,   IF_REAL,
                "Cross-term dependence of ketas"),
IO("pa1",               B3SOI_MOD_PA1,      IF_REAL,
                "Cross-term dependence of a1"),
IO("pa2",               B3SOI_MOD_PA2,      IF_REAL,
                "Cross-term dependence of a2"),
IO("prdsw",             B3SOI_MOD_PRDSW,    IF_REAL,
                "Cross-term dependence of rdsw"),
IO("pprwb",             B3SOI_MOD_PPRWB,    IF_REAL,
                "Cross-term dependence of prwb"),
IO("pprwg",             B3SOI_MOD_PPRWG,    IF_REAL,
                "Cross-term dependence of prwg"),
IO("pwr",               B3SOI_MOD_PWR,      IF_REAL,
                "Cross-term dependence of wr"),
IO("pnfactor",          B3SOI_MOD_PNFACTOR, IF_REAL,
                "Cross-term dependence of nfactor"),
IO("pdwg",              B3SOI_MOD_PDWG,     IF_REAL,
                "Cross-term dependence of dwg"),
IO("pdwb",              B3SOI_MOD_PDWB,     IF_REAL,
                "Cross-term dependence of dwb"),
IO("pvoff",             B3SOI_MOD_PVOFF,    IF_REAL,
                "Cross-term dependence of voff"),
IO("peta0",             B3SOI_MOD_PETA0,    IF_REAL,
                "Cross-term dependence of eta0"),
IO("petab",             B3SOI_MOD_PETAB,    IF_REAL,
                "Cross-term dependence of etab"),
IO("pdsub",             B3SOI_MOD_PDSUB,    IF_REAL,
                "Cross-term dependence of dsub"),
IO("pcit",              B3SOI_MOD_PCIT,     IF_REAL,
                "Cross-term dependence of cit"),
IO("pcdsc",             B3SOI_MOD_PCDSC,    IF_REAL,
                "Cross-term dependence of cdsc"),
IO("pcdscb",            B3SOI_MOD_PCDSCB,   IF_REAL,
                "Cross-term dependence of cdscb"),
IO("pcdscd",            B3SOI_MOD_PCDSCD,   IF_REAL,
                "Cross-term dependence of cdscd"),
IO("ppclm",             B3SOI_MOD_PPCLM,    IF_REAL,
                "Cross-term dependence of pclm"),
IO("ppdiblc1",          B3SOI_MOD_PPDIBL1,  IF_REAL,
                "Cross-term dependence of pdiblc1"),
IO("ppdiblc2",          B3SOI_MOD_PPDIBL2,  IF_REAL,
                "Cross-term dependence of pdiblc2"),
IO("ppdiblcb",          B3SOI_MOD_PPDIBLB,  IF_REAL,
                "Cross-term dependence of pdiblcb"),
IO("pdrout",            B3SOI_MOD_PDROUT,   IF_REAL,
                "Cross-term dependence of drout"),
IO("ppvag",             B3SOI_MOD_PPVAG,    IF_REAL,
                "Cross-term dependence of pvag"),
IO("pdelta",            B3SOI_MOD_PDELTA,   IF_REAL,
                "Cross-term dependence of delta"),
IO("palpha0",           B3SOI_MOD_PALPHA0,  IF_REAL,
                "Cross-term dependence of alpha0"),
IO("pfbjtii",           B3SOI_MOD_PFBJTII,  IF_REAL,
                "Cross-term dependence of fbjtii"),
IO("pbeta0",            B3SOI_MOD_PBETA0,   IF_REAL,
                "Cross-term dependence of beta0"),
IO("pbeta1",            B3SOI_MOD_PBETA1,   IF_REAL,
                "Cross-term dependence of beta1"),
IO("pbeta2",            B3SOI_MOD_PBETA2,   IF_REAL,
                "Cross-term dependence of beta2"),
IO("pvdsatii0",         B3SOI_MOD_PVDSATII0,IF_REAL,
                "Cross-term dependence of vdsatii0"),
IO("plii",              B3SOI_MOD_PLII,     IF_REAL,
                "Cross-term dependence of lii"),
IO("pesatii",           B3SOI_MOD_PESATII,  IF_REAL,
                "Cross-term dependence of esatii"),
IO("psii0",             B3SOI_MOD_PSII0,    IF_REAL,
                "Cross-term dependence of sii0"),
IO("psii1",             B3SOI_MOD_PSII1,    IF_REAL,
                "Cross-term dependence of sii1"),
IO("psii2",             B3SOI_MOD_PSII2,    IF_REAL,
                "Cross-term dependence of sii2"),
IO("psiid",             B3SOI_MOD_PSIID,    IF_REAL,
                "Cross-term dependence of siid"),
IO("pagidl",            B3SOI_MOD_PAGIDL,   IF_REAL,
                "Cross-term dependence of agidl"),
IO("pbgidl",            B3SOI_MOD_PBGIDL,   IF_REAL,
                "Cross-term dependence of bgidl"),
IO("pngidl",            B3SOI_MOD_PNGIDL,   IF_REAL,
                "Cross-term dependence of ngidl"),
IO("pntun",             B3SOI_MOD_PNTUN,    IF_REAL,
                "Cross-term dependence of ntun"),
IO("pndiode",           B3SOI_MOD_PNDIODE,  IF_REAL,
                "Cross-term dependence of ndiode"),
IO("pnrecf0",           B3SOI_MOD_PNRECF0,  IF_REAL,
                "Cross-term dependence of nrecf0"),
IO("pnrecr0",           B3SOI_MOD_PNRECR0,  IF_REAL,
                "Cross-term dependence of nrecr0"),
IO("pisbjt",            B3SOI_MOD_PISBJT,   IF_REAL,
                "Cross-term dependence of isbjt"),
IO("pisdif",            B3SOI_MOD_PISDIF,   IF_REAL,
                "Cross-term dependence of isdif"),
IO("pisrec",            B3SOI_MOD_PISREC,   IF_REAL,
                "Cross-term dependence of isrec"),
IO("pistun",            B3SOI_MOD_PISTUN,   IF_REAL,
                "Cross-term dependence of istun"),
IO("pvrec0",            B3SOI_MOD_PVREC0,   IF_REAL,
                "Cross-term dependence of vrec0"),
IO("pvtun0",            B3SOI_MOD_PVTUN0,   IF_REAL,
                "Cross-term dependence of vtun0"),
IO("pnbjt",             B3SOI_MOD_PNBJT,    IF_REAL,
                "Cross-term dependence of nbjt"),
IO("plbjt0",            B3SOI_MOD_PLBJT0,   IF_REAL,
                "Cross-term dependence of lbjt0"),
IO("pvabjt",            B3SOI_MOD_PVABJT,   IF_REAL,
                "Cross-term dependence of vabjt"),
IO("paely",             B3SOI_MOD_PAELY,    IF_REAL,
                "Cross-term dependence of aely"),
IO("pahli",             B3SOI_MOD_PAHLI,    IF_REAL,
                "Cross-term dependence of ahli"),
IO("pvsdfb",            B3SOI_MOD_PVSDFB,   IF_REAL,
                "Cross-term dependence of vsdfb"),
IO("pvsdth",            B3SOI_MOD_PVSDTH,   IF_REAL,
                "Cross-term dependence of vsdth"),
IO("pdelvt",            B3SOI_MOD_PDELVT,   IF_REAL,
                "Cross-term dependence of delvt"),
IO("pacde",             B3SOI_MOD_PACDE,    IF_REAL,
                "Cross-term dependence of acde"),
IO("pmoin",             B3SOI_MOD_PMOIN,    IF_REAL,
                "Cross-term dependence of amoin"),

IP("nmos",              B3SOI_MOD_NMOS,     IF_FLAG,
                "Flag to indicate NMOS"),
IP("pmos",              B3SOI_MOD_PMOS,     IF_FLAG,
                "Flag to indicate PMOS")
};

const char *B3SOInames[] = {
   "Drain",
   "Gate",
   "Source",
   "Substrate",
   "Backgate",
   "Body",
   "Temp"
};

const char *B3SOImodNames[] = {
    "nmos",
    "pmos",
    0
};

IFkeys B3SOIkeys[] = {
    IFkeys( 'm', B3SOInames, 4, 7, 0 )
};

} // namespace


B3SOIdev::B3SOIdev()
{
    dv_name = "BSIMSOI3.0";
    dv_description = "Berkeley SOI MOSFET Model Version 3.0";

    dv_numKeys = NUMELEMS(B3SOIkeys);
    dv_keys = B3SOIkeys;

    dv_levels[0] = 20;
    dv_levels[1] = 0;
    dv_modelKeys = B3SOImodNames;

    dv_numInstanceParms = NUMELEMS(B3SOIpTable);
    dv_instanceParms = B3SOIpTable;

    dv_numModelParms = NUMELEMS(B3SOImPTable);
    dv_modelParms = B3SOImPTable;

    dv_flags = DV_TRUNC;
};


sGENmodel *
B3SOIdev::newModl()
{
    return (new sB3SOImodel);
}


sGENinstance *
B3SOIdev::newInst()
{
    return (new sB3SOIinstance);
}


int
B3SOIdev::destroy(sGENmodel **model)
{
    return (IFdevice::destroy<sB3SOImodel, sB3SOIinstance>(model));
}


int
B3SOIdev::delInst(sGENmodel *model, IFuid dname, sGENinstance *fast)
{
    return (IFdevice::delInst<sB3SOImodel, sB3SOIinstance>(model, dname,
        fast));
}


int
B3SOIdev::delModl(sGENmodel **model, IFuid modname, sGENmodel *modfast)
{
    return (IFdevice::delModl<sB3SOImodel, sB3SOIinstance>(model, modname,
        modfast));
}


// mosfet parser
// Mname <node> <node> <node> <node> [<node> [<node> [<node>]]] <model>
//       [L=<val>] [W=<val>] [AD=<val>] [AS=<val>] [PD=<val>]
//       [PS=<val>] [NRD=<val>] [NRS=<val>] [OFF]
//       [IC=<val>,<val>,<val>]
// 
void
B3SOIdev::parse(int type, sCKT *ckt, sLine *current)
{
    DEV.parse(ckt, current, type, dv_keys->minTerms, dv_keys->maxTerms,
        true, 0);
}


void
B3SOIdev::backup(sGENmodel *mp, DEV_BKMODE m)
{
    while (mp) {
        for (sGENinstance *ip = mp->GENinstances; ip; ip = ip->GENnextInstance)
            ((sB3SOIinstance*)ip)->backup(m);
        mp = mp->GENnextModel;
    }
}


// Below is hugely GCC-specific.  The __WRMODULE__ and __WRVERSION__
// tokens are defined in the Makefile and passed with -D when
// compiling.

#define STR(x) #x
#define STRINGIFY(x) STR(x)
#define MCAT(x, y) x ## y
#define MODNAME(x, y) MCAT(x, y)

// Module initializer.  Sets locations in the main app to some
// identifying strings.
//
__attribute__((constructor)) static void initializer()
{
    extern const char *WRS_ModuleName, *WRS_ModuleVersion;

    WRS_ModuleName = STRINGIFY(__WRMODULE__);
    WRS_ModuleVersion = STRINGIFY(__WRVERSION__);
}


// Device constructor function.  This should be the only globally
// visible symbol in the module.  The function name expands to the
// module name with trailing _c.
// 
extern "C" {
    void
    MODNAME(__WRMODULE__, _c)(IFdevice **d, int *cnt)
    {
        *d = new B3SOIdev;
        (*cnt)++;
    }
}

