
/*========================================================================*
 *                                                                        *
 *  Distributed by Whiteley Research Inc., Sunnyvale, California, USA     *
 *                       http://wrcad.com                                 *
 *  Copyright (C) 2017 Whiteley Research Inc., all rights reserved.       *
 *  Author: Stephen R. Whiteley, except as indicated.                     *
 *                                                                        *
 *  As fully as possible recognizing licensing terms and conditions       *
 *  imposed by earlier work from which this work was derived, if any,     *
 *  this work is released under the Apache License, Version 2.0 (the      *
 *  "License").  You may not use this file except in compliance with      *
 *  the License, and compliance with inherited licenses which are         *
 *  specified in a sub-header below this one if applicable.  A copy       *
 *  of the License is provided with this distribution, or you may         *
 *  obtain a copy of the License at                                       *
 *                                                                        *
 *        http://www.apache.org/licenses/LICENSE-2.0                      *
 *                                                                        *
 *  See the License for the specific language governing permissions       *
 *  and limitations under the License.                                    *
 *                                                                        *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      *
 *   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES      *
 *   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-        *
 *   INFRINGEMENT.  IN NO EVENT SHALL WHITELEY RESEARCH INCORPORATED      *
 *   OR STEPHEN R. WHITELEY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER     *
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,      *
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE       *
 *   USE OR OTHER DEALINGS IN THE SOFTWARE.                               *
 *                                                                        *
 *========================================================================*
 *               XicTools Integrated Circuit Design System                *
 *                                                                        *
 * WRspice Circuit Simulation and Analysis Tool:  Device Library          *
 *                                                                        *
 *========================================================================*
 $Id:$
 *========================================================================*/

/***************************************************************************
JSPICE3 adaptation of Spice3f2 - Copyright (c) Stephen R. Whiteley 1992
Copyright 1990 Regents of the University of California.  All rights reserved.
Authors: 1987 Gary W. Ng
         1993 Stephen R. Whiteley
****************************************************************************/
/********** new in 3f2
Sydney University mods Copyright(c) 1989 Anthony E. Parker, David J. Skellern
    Laboratory for Communication Science Engineering
    Sydney University Department of Electrical Engineering, Australia
**********/

#include <stdio.h>
#include "jfetdefs.h"
#include "noisdefs.h"

// JFETnoise (mode, operation, firstModel, ckt, data, OnDens)
//    This routine names and evaluates all of the noise sources
//    associated with JFET's.  It starts with the model *firstModel and
//    traverses all of its insts.  It then proceeds to any other models
//    on the linked list.  The total output noise density generated by
//    all of the JFET's is summed with the variable "OnDens".

// define the names of the noise sources
static const char *JFETnNames[JFETNSRCS] = {
    // Note that we have to keep the order
    // consistent with the index definitions
    // in JFETdefs.h

    "_rd",      // noise due to rd
    "_rs",      // noise due to rs
    "_id",      // noise due to id
    "_1overf",  // flicker (1/f) noise
    ""          // total transistor noise
};


int
JFETdev::noise (int mode, int operation, sGENmodel *genmod, sCKT *ckt,
    sNdata *data, double *OnDens)
{
    char jfetname[N_MXVLNTH];
    sJFETmodel *model = static_cast<sJFETmodel*>(genmod);

    if (operation == N_OPEN) {
        // see if we have to to produce a summary report
        // if so, name all the noise generators
        if (static_cast<sNOISEAN*>(ckt->CKTcurJob)->NStpsSm == 0)
            return (OK);
        if (mode == N_DENS) {
            for ( ; model; model = model->next()) {
                sJFETinstance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {

                    for (int i = 0; i < JFETNSRCS; i++) {
                        (void)snprintf(jfetname, sizeof(jfetname),
                            "onoise_%s%s", (char*)inst->GENname,
                            JFETnNames[i]);
                        Realloc(&data->namelist, data->numPlots+1,
                            data->numPlots);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, jfetname, UID_OTHER);
                        // we've added one more plot
                    }
                }
            }
            return (OK);
        }

        if (mode == INT_NOIZ) {
            for ( ; model; model = model->next()) {
                sJFETinstance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {

                    for (int i = 0; i < JFETNSRCS; i++) {
                        (void)snprintf(jfetname, sizeof(jfetname),
                            "onoise_total_%s%s", (char*)inst->GENname,
                            JFETnNames[i]);
                        Realloc(&data->namelist, data->numPlots+2,
                            data->numPlots);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, jfetname, UID_OTHER);
                        (void)snprintf(jfetname, sizeof(jfetname),
                            "inoise_total_%s%s", (char*)inst->GENname,
                            JFETnNames[i]);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, jfetname, UID_OTHER);
                        // we've added two more plots
                    }
                }
            }
        }
        return (OK);
    }

    if (operation == N_CALC) {
        if (mode == N_DENS) {
            for ( ; model; model = model->next()) {
                sJFETinstance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {

                    double noizDens[JFETNSRCS];
                    double lnNdens[JFETNSRCS];
                    NevalSrc(&noizDens[JFETRDNOIZ], &lnNdens[JFETRDNOIZ],
                        ckt, THERMNOISE, inst->JFETdrainPrimeNode,
                        inst->JFETdrainNode,
                        model->JFETdrainConduct * inst->JFETarea);

                    NevalSrc(&noizDens[JFETRSNOIZ], &lnNdens[JFETRSNOIZ],
                        ckt, THERMNOISE, inst->JFETsourcePrimeNode,
                        inst->JFETsourceNode,
                        model->JFETsourceConduct*inst->JFETarea);

                    NevalSrc(&noizDens[JFETIDNOIZ], &lnNdens[JFETIDNOIZ],
                        ckt, THERMNOISE, inst->JFETdrainPrimeNode,
                        inst->JFETsourcePrimeNode,
                        (2.0/3.0 * FABS(*(ckt->CKTstate0 + inst->JFETgm))));

                    NevalSrc(&noizDens[JFETFLNOIZ], 0, ckt,
                        N_GAIN, inst->JFETdrainPrimeNode,
                        inst->JFETsourcePrimeNode, 0.0);

                    noizDens[JFETFLNOIZ] *= model->JFETfNcoef * 
                        exp(model->JFETfNexp *
                        log(SPMAX(FABS(*(ckt->CKTstate0 + inst->JFETcd)),
                        N_MINLOG))) / data->freq;

                    lnNdens[JFETFLNOIZ] = 
                        log(SPMAX(noizDens[JFETFLNOIZ], N_MINLOG));

                    noizDens[JFETTOTNOIZ] = noizDens[JFETRDNOIZ] +
                        noizDens[JFETRSNOIZ] + noizDens[JFETIDNOIZ] +
                        noizDens[JFETFLNOIZ];

                    lnNdens[JFETTOTNOIZ] = 
                        log(SPMAX(noizDens[JFETTOTNOIZ], N_MINLOG));

                    *OnDens += noizDens[JFETTOTNOIZ];

                    int i;
                    if (data->delFreq == 0.0) { 

                        // if we haven't done any previous integration,
                        // we need to initialize our "history" variables

                        for (i = 0; i < JFETNSRCS; i++)
                            inst->JFETnVar[LNLSTDENS][i] = lnNdens[i];

                        // clear out our integration variables if it's the
                        // first pass

                        if (data->freq ==
                                ((sNOISEAN*)ckt->CKTcurJob)->JOBac.fstart()) {

                            for (i = 0; i < JFETNSRCS; i++) {
                                inst->JFETnVar[OUTNOIZ][i] = 0.0;
                                inst->JFETnVar[INNOIZ][i] = 0.0;
                            }
                        }
                    }
                    else {
                        // data->delFreq != 0.0 (we have to integrate)

                        for (i = 0; i < JFETNSRCS; i++) {
                            if (i != JFETTOTNOIZ) {
                                double tempOnoise;
                                double tempInoise;
                                tempOnoise = data->integrate(noizDens[i],
                                    lnNdens[i], inst->JFETnVar[LNLSTDENS][i]);
                                tempInoise = data->integrate(noizDens[i]*
                                    data->GainSqInv,
                                    lnNdens[i] + data->lnGainInv,
                                    inst->JFETnVar[LNLSTDENS][i] +
                                    data->lnGainInv);
                                inst->JFETnVar[LNLSTDENS][i] = lnNdens[i];
                                data->outNoiz += tempOnoise;
                                data->inNoise += tempInoise;
                                if (((sNOISEAN*)ckt->CKTcurJob)->NStpsSm
                                        != 0) {
                                    inst->JFETnVar[OUTNOIZ][i] += tempOnoise;
                                    inst->JFETnVar[OUTNOIZ][JFETTOTNOIZ] +=
                                        tempOnoise;
                                    inst->JFETnVar[INNOIZ][i] += tempInoise;
                                    inst->JFETnVar[INNOIZ][JFETTOTNOIZ] +=
                                        tempInoise;
                                }
                            }
                        }
                    }
                    if (data->prtSummary) {
                        for (i = 0; i < JFETNSRCS; i++) {
                            // print a summary report
                            data->outpVector[data->outNumber++] = noizDens[i];
                        }
                    }
                }
            }
            return (OK);
        }

        if (mode == INT_NOIZ) {
            // already calculated, just output
            if (static_cast<sNOISEAN*>(ckt->CKTcurJob)->NStpsSm == 0)
                return (OK);
            for ( ; model; model = model->next()) {
                sJFETinstance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {

                    for (int i = 0; i < JFETNSRCS; i++) {
                        data->outpVector[data->outNumber++] =
                            inst->JFETnVar[OUTNOIZ][i];
                        data->outpVector[data->outNumber++] =
                            inst->JFETnVar[INNOIZ][i];
                    }
                }
            }
        }
    }

    return (OK);
}
            

