#! /bin/bash

# Make sure package directories symbolic links are created.

exprog=./exported
oses=$($exprog oses)

for a in $oses; do
    if [ ! -d $HOME/wrcad.com/html/xictools/$a ]; then
        mkdir $HOME/wrcad.com/html/xictools/$a
    fi
    if [ ! -e $HOME/wrcad.com/html/xictools/$a/wr_install ]; then
        ln -s ../scripts/wr_install $HOME/wrcad.com/html/xictools/$a
    fi
    if [ ! -e $HOME/wrcad.com/html/xictools/$a/wr_uninstall ]; then
        ln -s ../scripts/wr_uninstall $HOME/wrcad.com/html/xictools/$a
    fi
done

if [ -d $HOME/wrcad.com/html/xictools/Win32 ]; then
    if [ ! -e $HOME/wrcad.com/html/xictools/Win32/cleanold.bat ]; then
        ln -s ../scripts/cleanold.bat $HOME/wrcad.com/html/xictools/Win32
    fi
    if [ ! -e $HOME/wrcad.com/html/xictools/Win32/uninstall.bat ]; then
        ln -s ../scripts/uninstall.bat $HOME/wrcad.com/html/xictools/Win32
    fi
fi

