#! /bin/sh

# Upload the "stable" scripts.  Do this (of course) when these scripts
# change.

# Change these if you're not me.
login=stevew
srcdir=/home/$login/src/xt/xt_base/www/upload

# SSH command, note alternate port.
sshcmd="ssh -p 2222"

sshc=$SSH_CONNECTION
if [ -z "$sshc" ]; then
    echo "Can't get home IP, exiting"
    exit
fi
set -- $sshc
home=$1
echo Connecting to $home

files="fetchnew mklinks mktab refresh update update_help update_man \
 upload wupd xupd"
for f in $files; do
    echo uploading $f
    rsync --rsh="$sshcmd" $login@$home:$srcdir/$f .
    if [ ! -f $f ]; then
        echo "Error: failed to upload \'$f\' script."
    fi
    if [ ! -x $f ]; then
        chmod 755 $f
    fi
done

f=README
if [ -n "$f" ]; then
    echo uploading $f
    rsync --rsh="$sshcmd" $login@$home:$srcdir/$f .
    if [ ! -f $f ]; then
        echo "Error: failed to upload \'$f\' script."
    fi
fi

