
/*========================================================================*
 *                                                                        *
 *  Distributed by Whiteley Research Inc., Sunnyvale, California, USA     *
 *                       http://wrcad.com                                 *
 *  Copyright (C) 2017 Whiteley Research Inc., all rights reserved.       *
 *  Author: Stephen R. Whiteley, except as indicated.                     *
 *                                                                        *
 *  As fully as possible recognizing licensing terms and conditions       *
 *  imposed by earlier work from which this work was derived, if any,     *
 *  this work is released under the Apache License, Version 2.0 (the      *
 *  "License").  You may not use this file except in compliance with      *
 *  the License, and compliance with inherited licenses which are         *
 *  specified in a sub-header below this one if applicable.  A copy       *
 *  of the License is provided with this distribution, or you may         *
 *  obtain a copy of the License at                                       *
 *                                                                        *
 *        http://www.apache.org/licenses/LICENSE-2.0                      *
 *                                                                        *
 *  See the License for the specific language governing permissions       *
 *  and limitations under the License.                                    *
 *                                                                        *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      *
 *   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES      *
 *   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-        *
 *   INFRINGEMENT.  IN NO EVENT SHALL WHITELEY RESEARCH INCORPORATED      *
 *   OR STEPHEN R. WHITELEY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER     *
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,      *
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE       *
 *   USE OR OTHER DEALINGS IN THE SOFTWARE.                               *
 *                                                                        *
 *========================================================================*
 *               XicTools Integrated Circuit Design System                *
 *                                                                        *
 * WRspice Circuit Simulation and Analysis Tool:  Device Library          *
 *                                                                        *
 *========================================================================*
 $Id:$
 *========================================================================*/

/***************************************************************************
JSPICE3 adaptation of Spice3f2 - Copyright (c) Stephen R. Whiteley 1992
Copyright 1990 Regents of the University of California.  All rights reserved.
Authors: 1987 Gary W. Ng
         1993 Stephen R. Whiteley
****************************************************************************/

#include <stdio.h>
#include "mosdefs.h"
#include "noisdefs.h"

//    This routine names and evaluates all of the noise sources
//    associated with MOSFET's.  It starts with the model *firstModel and
//    traverses all of its insts.  It then proceeds to any other models
//    on the linked list.  The total output noise density generated by
//    all of the MOSFET's is summed with the variable "OnDens".
//

// define the names of the noise sources
static const char *MOSnNames[MOSNSRCS] = {
    // Note that we have to keep the order consistent with the index
    // definitions in MOSdefs.h
    //
    "_rd",      // noise due to rd
    "_rs",      // noise due to rs
    "_id",      // noise due to id
    "_1overf",  // flicker (1/f) noise
    ""          // total transistor noise
};


int
MOSdev::noise (int mode, int operation, sGENmodel *genmod, sCKT *ckt,
    sNdata *data, double *OnDens)
{
    // Oxide capacitance can be zero in MOS level 1.  Since this will
    // give us problems in our 1/f noise model, we ASSUME an actual "tox"
    // of 1e-7

    sMOSmodel *model = static_cast<sMOSmodel*>(genmod);
    char mosname[N_MXVLNTH];
    if (operation == N_OPEN) {
        // see if we have to to produce a summary report
        // if so, name all the noise generators
        if (static_cast<sNOISEAN*>(ckt->CKTcurJob)->NStpsSm == 0)
            return (OK);

        if (mode == N_DENS) {
            for ( ; model; model = model->next()) {
                double coxSquared;
                if (model->MOSoxideCapFactor == 0.0)
                    coxSquared = 3.9 * 8.854214871e-12 / 1e-7;
                else
                    coxSquared = model->MOSoxideCapFactor;
                coxSquared *= coxSquared;

                sMOSinstance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {
                    for (int i = 0; i < MOSNSRCS; i++) {
                        (void)snprintf(mosname, sizeof(mosname), "onoise_%s%s",
                            (char*)inst->GENname, MOSnNames[i]);
                        Realloc(&data->namelist, data->numPlots+1,
                            data->numPlots);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, mosname, UID_OTHER);
                        // we've added one more plot
                    }
                }
            }
            return (OK);
        }

        if (mode == INT_NOIZ) {
            for ( ; model; model = model->next()) {
                double coxSquared;
                if (model->MOSoxideCapFactor == 0.0)
                    coxSquared = 3.9 * 8.854214871e-12 / 1e-7;
                else
                    coxSquared = model->MOSoxideCapFactor;
                coxSquared *= coxSquared;

                sMOSinstance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {
                    for (int i = 0; i < MOSNSRCS; i++) {
                        (void)snprintf(mosname, sizeof(mosname),
                            "onoise_total_%s%s", (char*)inst->GENname,
                            MOSnNames[i]);
                        Realloc(&data->namelist, data->numPlots+2,
                            data->numPlots);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, mosname, UID_OTHER);
                        (void)snprintf(mosname, sizeof(mosname),
                            "inoise_total_%s%s", (char*)inst->GENname,
                            MOSnNames[i]);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, mosname, UID_OTHER);
                        // we've added two more plots
                    }
                }
            }
        }
        return (OK);
    }

#define MSC(xx) inst->MOSmult*(xx)

    if (operation == N_CALC) {
        if (mode == N_DENS) {
            for ( ; model; model = model->next()) {
                double coxSquared;
                if (model->MOSoxideCapFactor == 0.0)
                    coxSquared = 3.9 * 8.854214871e-12 / 1e-7;
                else
                    coxSquared = model->MOSoxideCapFactor;
                coxSquared *= coxSquared;

                sMOSinstance *inst;
                double noizDens[MOSNSRCS];
                double lnNdens[MOSNSRCS];
                for (inst = model->inst(); inst; inst = inst->next()) {
                    NevalSrc(&noizDens[MOSRDNOIZ],
                        &lnNdens[MOSRDNOIZ],
                        ckt, THERMNOISE, inst->MOSdNodePrime,
                        inst->MOSdNode, MSC(inst->MOSdrainConductance));

                    NevalSrc(&noizDens[MOSRSNOIZ],
                        &lnNdens[MOSRSNOIZ],
                        ckt, THERMNOISE, inst->MOSsNodePrime,
                        inst->MOSsNode, MSC(inst->MOSsourceConductance));

                    NevalSrc(&noizDens[MOSIDNOIZ],
                        &lnNdens[MOSIDNOIZ],
                        ckt, THERMNOISE, inst->MOSdNodePrime,
                        inst->MOSsNodePrime,
                        MSC(2.0/3.0 * FABS(inst->MOSgm)));

                    NevalSrc(&noizDens[MOSFLNOIZ], 0, ckt,
                        N_GAIN, inst->MOSdNodePrime,
                        inst->MOSsNodePrime, 0.0);

                    noizDens[MOSFLNOIZ] *= MSC(model->MOSfNcoef) * 
                        exp(model->MOSfNexp *
                        log(SPMAX(FABS(inst->MOScd), N_MINLOG))) /
                        (data->freq * inst->MOSw * 
                        (inst->MOSl - 2*model->MOSlatDiff) *
                        coxSquared);

                    lnNdens[MOSFLNOIZ] = 
                        log(SPMAX(noizDens[MOSFLNOIZ], N_MINLOG));

                    noizDens[MOSTOTNOIZ] = noizDens[MOSRDNOIZ] +
                        noizDens[MOSRSNOIZ] +
                        noizDens[MOSIDNOIZ] +
                        noizDens[MOSFLNOIZ];

                    lnNdens[MOSTOTNOIZ] = 
                        log(SPMAX(noizDens[MOSTOTNOIZ], N_MINLOG));

                    *OnDens += noizDens[MOSTOTNOIZ];

                    if (data->delFreq == 0.0) {
                        // if we haven't done any previous
                        // integration, we need to initialize
                        // our "history" variables

                        for (int i = 0; i < MOSNSRCS; i++)
                            inst->MOSnVar[LNLSTDENS][i] = lnNdens[i];

                        // clear out our integration variables if
                        // it's the first pass

                        if (data->freq ==
                                static_cast<sNOISEAN*>
                                (ckt->CKTcurJob)->JOBac.fstart()) {

                            for (int i = 0; i < MOSNSRCS; i++) {
                                inst->MOSnVar[OUTNOIZ][i] = 0.0;
                                inst->MOSnVar[INNOIZ][i] = 0.0;
                            }
                        }
                    }
                    else {
                        // data->delFreq != 0.0
                        // (we have to integrate)
                        ///
                        for (int i = 0; i < MOSNSRCS; i++) {
                            double tempOnoise;
                            double tempInoise;
                            if (i != MOSTOTNOIZ) {
                                tempOnoise = data->integrate(noizDens[i],
                                    lnNdens[i], inst->MOSnVar[LNLSTDENS][i]);
                                tempInoise = data->integrate(noizDens[i]*
                                    data->GainSqInv,
                                    lnNdens[i] + data->lnGainInv,
                                    inst->MOSnVar[LNLSTDENS][i] +
                                    data->lnGainInv);
                                inst->MOSnVar[LNLSTDENS][i] = lnNdens[i];
                                data->outNoiz += tempOnoise;
                                data->inNoise += tempInoise;
                                if (((sNOISEAN*)ckt->CKTcurJob)->NStpsSm
                                        != 0) {
                                    inst->MOSnVar[OUTNOIZ][i] += tempOnoise;
                                    inst->MOSnVar[OUTNOIZ][MOSTOTNOIZ] +=
                                        tempOnoise;
                                    inst->MOSnVar[INNOIZ][i] += tempInoise;
                                    inst->MOSnVar[INNOIZ][MOSTOTNOIZ] +=
                                        tempInoise;

                                }
                            }
                        }
                    }
                    if (data->prtSummary) {
                        for (int i = 0; i < MOSNSRCS; i++) {
                            // print a summary report
                            data->outpVector[data->outNumber++] =
                                noizDens[i];
                        }
                    }
                }
            }
            return (OK);
        }
        
        if (mode == INT_NOIZ) {
            // already calculated, just output
            if (((sNOISEAN*)ckt->CKTcurJob)->NStpsSm == 0)
                return (OK);
            for ( ; model; model = model->next()) {
                double coxSquared;
                if (model->MOSoxideCapFactor == 0.0)
                    coxSquared = 3.9 * 8.854214871e-12 / 1e-7;
                else
                    coxSquared = model->MOSoxideCapFactor;
                coxSquared *= coxSquared;

                sMOSinstance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {
                    for (int i = 0; i < MOSNSRCS; i++) {
                        data->outpVector[data->outNumber++] =
                            inst->MOSnVar[OUTNOIZ][i];
                        data->outpVector[data->outNumber++] =
                            inst->MOSnVar[INNOIZ][i];
                    }
                }
            }
        }
    }
    return (OK);
}
