#!/bin/sh
# $Id: install_bin,v 1.1 2004/09/21 19:41:18 stevew Exp $
# Install a binary target
#
if [ $# = 2 ]; then
    if [ -d $2 ]; then
        target=$2/`basename $1`
    else
        target=$2
    fi
    if [ -f $target ]; then
        rm -f $target
    fi
    cp $1 $target
    if [ -f $target ]; then
        if [ "x`file $target |grep executable`" != "x" ]; then
            strip $target
        fi
        chmod 0755 $target
        chown bin:bin $target
    fi
fi
