# Generated automatically from Makefile.in by configure.
#######################################################################
# util/Makefile.in
#######################################################################
# $Id: Makefile.in,v 1.2 2009/04/08 17:25:06 stevew Exp $
#######################################################################

DATE = Sun Jun 18 13:38:56 PDT 2017
CXX = /usr/local/win-builds/bin/g++
CC = /usr/local/win-builds/bin/gcc

#all: datestr timegen

#datestr: datestr.c
#	$(CC) -o datestr datestr.c

timegen: timegen.cc
	$(CXX) -o timegen timegen.cc

clean distclean:
	rm -f datestr timegen
