#######################################################################
# util/Makefile.in
#######################################################################
# $Id: Makefile.in,v 1.2 2009/04/08 17:25:06 stevew Exp $
#######################################################################

DATE = Thu Jun 15 22:08:57 PDT 2017
CXX = g++
CC = gcc

#all: datestr timegen

#datestr: datestr.c
#	$(CC) -o datestr datestr.c

timegen: timegen.cc
	$(CXX) -o timegen timegen.cc

clean:
	rm -f datestr timegen
