#! /bin/sh

# $Id: mvdir,v 1.2 2010/09/29 06:15:23 stevew Exp $

# Recursively copy a directory tree with the aid of special Makefile
# targets.

av0=$0
mkdir $2
pushd $1
files=`make files`
sdirs=`make subdirs`
popd

act=false
for a in $files; do
    if [ $a = "[" ]; then
        act=true
        continue
    fi
    if [ $a = "]" ]; then
        break
    fi
    if [ $act = true ]; then
        cp -pf $1/$a $2/$a
    fi
done

act=false
for a in $subdirs; do
    if [ $a = "[" ]; then
        act=true
        continue
    fi
    if [ $a = "]" ]; then
        break
    fi
    if [ $act = true ]; then
        $av0 $1/$a $2/$a
    fi
done

