#! /bin/sh

# Create the Makefile by copying the template and substituting text.

# mextram
SOURCE=bjt504.va
#SOURCE=bjt504t.va
#SOURCE=bjt504.va
#SOURCE=bjtd504t.va
#SOURCE=bjtd504.va
MODELNAME=bjt504va
#MODELNAME=bjt504tva
#MODELNAME=bjt504va
#MODELNAME=bjtd504tva
#MODELNAME=bjtd504va
MODULE=bjt504
#MODULE=bjt504t
#MODULE=bjt504
#MODULE=bjtd504t
#MODULE=bjtd504
KEY=q
LEVEL=6
# Give other devices a different level.
ADD_M=no
PREDICTOR=yes
LIMITING=yes
FLAGS=DV_NODIST

cat ../../Makefile | sed \
  -e "s%^SOURCE = .*%SOURCE = $SOURCE%" \
  -e "s%^MODELNAME = .*%MODELNAME = $MODELNAME%" \
  -e "s%^MODULE = .*%MODULE = $MODULE%" \
  -e "s%^KEY = .*%KEY = $KEY%" \
  -e "s%^LEVEL = .*%LEVEL = $LEVEL%" \
  -e "s%^ADD_M = .*%ADD_M = $ADD_M%" \
  -e "s%^PREDICTOR = .*%PREDICTOR = $PREDICTOR%" \
  -e "s%^LIMITING = .*%LIMITING = $LIMITING%" \
  -e "s%^FLAGS = .*%FLAGS = $FLAGS%" \
  > Makefile

