#! /bin/sh

# Create the Makefile by copying the template and substituting text.

# mextram
SOURCE=bjt505.va
#SOURCE=bjt505t.va
#SOURCE=bjt505.va
#SOURCE=bjtd505t.va
#SOURCE=bjtd505.va
MODELNAME=bjt505va
#MODELNAME=bjt505tva
#MODELNAME=bjt505va
#MODELNAME=bjtd505tva
#MODELNAME=bjtd505va
MODULE=bjt505
#MODULE=bjt505t
#MODULE=bjt505
#MODULE=bjtd505t
#MODULE=bjtd505
KEY=q
LEVEL=6
# Give other devices a different level.
ADD_M=no
PREDICTOR=yes
LIMITING=yes
FLAGS=DV_NODIST

cat ../../Makefile | sed \
  -e "s%^SOURCE = .*%SOURCE = $SOURCE%" \
  -e "s%^MODELNAME = .*%MODELNAME = $MODELNAME%" \
  -e "s%^MODULE = .*%MODULE = $MODULE%" \
  -e "s%^KEY = .*%KEY = $KEY%" \
  -e "s%^LEVEL = .*%LEVEL = $LEVEL%" \
  -e "s%^ADD_M = .*%ADD_M = $ADD_M%" \
  -e "s%^PREDICTOR = .*%PREDICTOR = $PREDICTOR%" \
  -e "s%^LIMITING = .*%LIMITING = $LIMITING%" \
  -e "s%^FLAGS = .*%FLAGS = $FLAGS%" \
  > Makefile

