
HFILES = \
  gtkedit.h gtkfile.h gtkfont.h gtkhcopy.h gtkinterf.h gtklist.h \
  gtkmcol.h gtkpfiles.h gtksearch.h gtkspinbtn.h gtkutil.h gtkx11.h \
  mswdraw.h mswpdev.h

files::
	@echo [ $(HFILES) ]

subdirs::
	@echo [

