
HFILES = \
  atomic_stack.h childproc.h coresize.h crypt.h encode.h errorrec.h \
  filestat.h hashfunc.h largefile.h lstring.h miscmath.h miscutil.h \
  msw.h pathlist.h quicksort.h random.h randval.h rangetest.h \
  services.h smartarray.h symtab.h texttf.h threadpool.h timedbg.h \
  timer.h tvals.h

files::
	@echo [ $(HFILES) ]

subdirs::
	@echo [

