#! /bin/sh

# This script will attempt to find and print
#   1.  the host name
#   2.  the IP address
#   3.  The host id (Solaris) or the ethernet address (FreeBSD, Linux)

# No copyright, public domain

hostname=`hostname`
echo Your host name is: $hostname

ip=`traceroute $hostname 2>&1 | grep traceroute | sed s/.*\(// | sed s/\).*//`
echo Your IP address is: $ip

if [ `uname` = "SunOS" ]; then
    echo Your Host ID is: `hostid`
else
    hw=`ifconfig -a | grep ether | sed s/"^.*ether *"//`
    if [ -z "$hw" ]; then
        hw=`ifconfig -a | grep HWaddr | sed s/"^.*HWaddr *"//`
    fi
fi 
if [ -n "$hw" ]; then
    set $hw
    echo Your ethernet address is: $1
fi
