#! /bin/sh
#
# This is where the release numbers are set.
#

release="4"
tools_version="4.2"
xtlserv_version="4.2.3"

if [ z$1 != "z" ]; then
    case $1 in
    release)
        echo $release
        ;;
    tools)
        echo $tools_version
        ;;
    xtlserv)
        echo $xtlserv_version
        ;;
    esac
fi

