#! /bin/sh

# Create the Makefile by copying the template and substituting text.

# ekv
SOURCE=ekv.va
MODELNAME=ekv26
MODULE=ekv26
KEY=m
LEVEL=44
ADD_M=yes
PREDICTOR=yes
LIMITING=yes
FLAGS=DV_NODIST

cat ../../Makefile | sed \
  -e "s%^SOURCE = .*%SOURCE = $SOURCE%" \
  -e "s%^MODELNAME = .*%MODELNAME = $MODELNAME%" \
  -e "s%^MODULE = .*%MODULE = $MODULE%" \
  -e "s%^KEY = .*%KEY = $KEY%" \
  -e "s%^LEVEL = .*%LEVEL = $LEVEL%" \
  -e "s%^ADD_M = .*%ADD_M = $ADD_M%" \
  -e "s%^PREDICTOR = .*%PREDICTOR = $PREDICTOR%" \
  -e "s%^LIMITING = .*%LIMITING = $LIMITING%" \
  -e "s%^FLAGS = .*%FLAGS = $FLAGS%" \
  > Makefile

