#! /bin/sh
#
# This is where the release numbers are set.
#

release="4"
tools_version="4.3"
xic_version="4.3.1"

if [ z$1 != "z" ]; then
    case $1 in
    release)
        echo $release
        ;;
    tools)
        echo $tools_version
        ;;
    xic | xicii | xiv)
        echo $xic_version
        ;;
    esac
fi

