#! /bin/sh

# Create the Makefile by copying the template and substituting text.

# psp102
SOURCE=psp102.va
#SOURCE=psp102b_nqs.va
#SOURCE=psp102e_nqs.va
#SOURCE=psp102_nqs.va
#SOURCE=psp102b.va
#SOURCE=psp102e.va
MODELNAME=PSP102VA
MODULE=psp102
#MODULE=psp102b_nqs
#MODULE=psp102e_nqs
#MODULE=psp102_nqs
#MODULE=psp102b
#MODULE=psp102e
KEY=m
LEVEL=45
ADD_M=yes
LIMITING=yes
FLAGS=DV_NODIST

cat ../../Makefile | sed \
  -e "s%^SOURCE = .*%SOURCE = $SOURCE%" \
  -e "s%^MODELNAME = .*%MODELNAME = $MODELNAME%" \
  -e "s%^MODULE = .*%MODULE = $MODULE%" \
  -e "s%^KEY = .*%KEY = $KEY%" \
  -e "s%^LEVEL = .*%LEVEL = $LEVEL%" \
  -e "s%^ADD_M = .*%ADD_M = $ADD_M%" \
  -e "s%^LIMITING = .*%LIMITING = $LIMITING%" \
  -e "s%^FLAGS = .*%FLAGS = $FLAGS%" \
  > Makefile

