
HFILES = \
  fontutil.h gr_pkg_setup.h graphics.h grfont.h grlinedb.h hpgl.h \
  nulldev.h pcl.h pixtab.h polydecomp.h psbc.h psbm.h pslindrw.h \
  raster.h rgbmap.h rgbzimg.h shmctl.h xdraw.h xfig.h

files::
	@echo [ $(HFILES) ]

subdirs::
	@echo [

