#! /bin/sh

# Previously, FastHenry-3.0wr was versioned by a date code.  The
# present framework requires a "1.2.3" format for version.  We'll keep
# 3.0 for major/minor, and increment the release.  The 090919
# distribution is release number 14.

release_num=14

echo 3.0.$release_num

