#! /bin/sh

# Create the Makefile by copying the template and substituting text.

# hicum
#SOURCE=hicumL2V2p32.va
SOURCE=hicumL2V2p4p0.va
MODELNAME=hic2_full
MODULE=hicum2
KEY=q
LEVEL=8
ADD_M=no
PREDICTOR=yes
LIMITING=yes
FLAGS=DV_NODIST

cat ../../Makefile | sed \
  -e "s%^SOURCE = .*%SOURCE = $SOURCE%" \
  -e "s%^MODELNAME = .*%MODELNAME = $MODELNAME%" \
  -e "s%^MODULE = .*%MODULE = $MODULE%" \
  -e "s%^KEY = .*%KEY = $KEY%" \
  -e "s%^LEVEL = .*%LEVEL = $LEVEL%" \
  -e "s%^ADD_M = .*%ADD_M = $ADD_M%" \
  -e "s%^PREDICTOR = .*%PREDICTOR = $PREDICTOR%" \
  -e "s%^LIMITING = .*%LIMITING = $LIMITING%" \
  -e "s%^FLAGS = .*%FLAGS = $FLAGS%" \
  > Makefile

