#! /bin/sh

# This release is in sync with qrouter-1.3.62.

# Here is where the release number is defined.  Presently, although
# the LDDB and MRouter could be compiled as separate components, we
# merge all code and build a common library.  Thus, for now we need
# only one release version.
#
# ***** IMPORTANT *****
#
# The version is in the form major.minor.release.
# >  The 'major' value is fixed at 1 for now.
# >  The 'minor' value is the "interface level" and is incremented if the
#    exported headers materially change.
# >  The 'release" value is incremented for bug fixes and code changes
#    that don't affect the interface.
#
# The application using the plug-in should check the major and minor
# value and disallow loading if mismatched.  Testing of the release
# value is optional.  If mismatched, features may be missing, but
# there should not be faults due to interface differences.

# The current Interface level is 1, corresponding to
# lddb.h    1.19
# ld_util.h 1.4
# mrouter.h 1.9

version="1.1.1"

echo $version

