
/*========================================================================*
 *                                                                        *
 *  Distributed by Whiteley Research Inc., Sunnyvale, California, USA     *
 *                       http://wrcad.com                                 *
 *  Copyright (C) 2017 Whiteley Research Inc., all rights reserved.       *
 *  Author: Stephen R. Whiteley, except as indicated.                     *
 *                                                                        *
 *  As fully as possible recognizing licensing terms and conditions       *
 *  imposed by earlier work from which this work was derived, if any,     *
 *  this work is released under the Apache License, Version 2.0 (the      *
 *  "License").  You may not use this file except in compliance with      *
 *  the License, and compliance with inherited licenses which are         *
 *  specified in a sub-header below this one if applicable.  A copy       *
 *  of the License is provided with this distribution, or you may         *
 *  obtain a copy of the License at                                       *
 *                                                                        *
 *        http://www.apache.org/licenses/LICENSE-2.0                      *
 *                                                                        *
 *  See the License for the specific language governing permissions       *
 *  and limitations under the License.                                    *
 *                                                                        *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      *
 *   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES      *
 *   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-        *
 *   INFRINGEMENT.  IN NO EVENT SHALL WHITELEY RESEARCH INCORPORATED      *
 *   OR STEPHEN R. WHITELEY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER     *
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,      *
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE       *
 *   USE OR OTHER DEALINGS IN THE SOFTWARE.                               *
 *                                                                        *
 *========================================================================*
 *               XicTools Integrated Circuit Design System                *
 *                                                                        *
 * WRspice Circuit Simulation and Analysis Tool:  Device Library          *
 *                                                                        *
 *========================================================================*
 $Id:$
 *========================================================================*/

/**********
based on jfetnoi.c
Copyright 1990 Regents of the University of California.  All rights reserved.
Author: 1987 Gary W. Ng

Modified to jfet2 for PS model definition ( Anthony E. Parker )
   Copyright 1994  Macquarie University, Sydney Australia.
**********/

#include <stdio.h>
#include "jfet2defs.h"
#include "noisdefs.h"

#define JFET2nextModel      next()
#define JFET2nextInstance   next()
#define JFET2instances      inst()
#define JFET2name GENname
#define MAX SPMAX
#define NOISEAN sNOISEAN
#define Nintegrate(a, b, c, d) (d)->integrate(a, b, c)
#define NstartFreq JOBac.fstart()

//
// JFET2noise (mode, operation, firstModel, ckt, data, OnDens)
//    This routine names and evaluates all of the noise sources
//    associated with JFET2's.  It starts with the model *firstModel and
//    traverses all of its insts.  It then proceeds to any other models
//    on the linked list.  The total output noise density generated by
//    all of the JFET2's is summed with the variable "OnDens".
// 

// define the names of the noise sources
static const char *JFET2nNames[JFET2NSRCS] = {
    // Note that we have to keep the order consistent with the index
    // definitions in JFET2defs.h

    "_rd",      // noise due to rd
    "_rs",      // noise due to rs
    "_id",      // noise due to id
    "_1overf",  // flicker (1/f) noise
    ""          // total transistor noise
};


int
JFET2dev::noise (int mode, int operation, sGENmodel *genmod, sCKT *ckt,
    sNdata *data, double *OnDens)
{
    char jfet2name[N_MXVLNTH];
    sJFET2model *model = static_cast<sJFET2model*>(genmod);

    if (operation == N_OPEN) {
        // see if we have to to produce a summary report
        // if so, name all the noise generators
        if (((NOISEAN*)ckt->CKTcurJob)->NStpsSm == 0)
            return (OK);
        if (mode == N_DENS) {
            for ( ; model; model = model->next()) {
                sJFET2instance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {
                    for (int i = 0; i < JFET2NSRCS; i++) {
                        (void)snprintf(jfet2name, sizeof(jfet2name),
                            "onoise_%s%s", (char*)inst->JFET2name,
                            JFET2nNames[i]);

                        Realloc(&data->namelist, data->numPlots+1,
                            data->numPlots);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, jfet2name, UID_OTHER);
                        // we've added one more plot
                    }
                }
            }
            return (OK);
        }

        if (mode == INT_NOIZ) {
            for ( ; model; model = model->next()) {
                sJFET2instance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {
                    for (int i = 0; i < JFET2NSRCS; i++) {
                        (void)snprintf(jfet2name, sizeof(jfet2name),
                            "onoise_total_%s%s", (char*)inst->JFET2name,
                            JFET2nNames[i]);
                        Realloc(&data->namelist, data->numPlots+2,
                            data->numPlots);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, jfet2name, UID_OTHER);
                        // we've added one more plot

                        (void)snprintf(jfet2name, sizeof(jfet2name),
                            "inoise_total_%s%s", (char*)inst->JFET2name,
                            JFET2nNames[i]);
                        ckt->newUid(&data->namelist[data->numPlots++],
                            0, jfet2name, UID_OTHER);
                        // we've added one more plot
                    }
                }
            }
        }
        return (OK);
    }

    if (operation == N_CALC) {
        if (mode ==  N_DENS) {
            for ( ; model; model = model->next()) {
                sJFET2instance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {
                    double noizDens[JFET2NSRCS];
                    double lnNdens[JFET2NSRCS];

                    NevalSrc(&noizDens[JFET2RDNOIZ], &lnNdens[JFET2RDNOIZ],
                        ckt, THERMNOISE, inst->JFET2drainPrimeNode,
                        inst->JFET2drainNode,
                        model->JFET2drainConduct * inst->JFET2area);

                    NevalSrc(&noizDens[JFET2RSNOIZ], &lnNdens[JFET2RSNOIZ],
                        ckt, THERMNOISE, inst->JFET2sourcePrimeNode,
                        inst->JFET2sourceNode,
                        model->JFET2sourceConduct*inst->JFET2area);

                    NevalSrc(&noizDens[JFET2IDNOIZ], &lnNdens[JFET2IDNOIZ],
                        ckt, THERMNOISE, inst->JFET2drainPrimeNode,
                        inst->JFET2sourcePrimeNode,
                        (2.0/3.0 * FABS(*(ckt->CKTstate0 + inst->JFET2gm))));

                    NevalSrc(&noizDens[JFET2FLNOIZ], (double*)NULL, ckt,
                        N_GAIN,inst->JFET2drainPrimeNode,
                        inst->JFET2sourcePrimeNode, 0.0);
                    noizDens[JFET2FLNOIZ] *= model->JFET2fNcoef * 
                        exp(model->JFET2fNexp *
                        log(MAX(FABS(*(ckt->CKTstate0 +
                        inst->JFET2cd)),N_MINLOG))) / data->freq;
                    lnNdens[JFET2FLNOIZ] = 
                        log(MAX(noizDens[JFET2FLNOIZ],N_MINLOG));

                    noizDens[JFET2TOTNOIZ] = noizDens[JFET2RDNOIZ] +
                        noizDens[JFET2RSNOIZ] + noizDens[JFET2IDNOIZ] +
                        noizDens[JFET2FLNOIZ];
                    lnNdens[JFET2TOTNOIZ] = 
                        log(MAX(noizDens[JFET2TOTNOIZ], N_MINLOG));

                    *OnDens += noizDens[JFET2TOTNOIZ];

                    if (data->delFreq == 0.0) { 

                        // if we haven't done any previous integration,
                        // we need to initialize our "history" variables

                        for (int i = 0; i < JFET2NSRCS; i++)
                            inst->JFET2nVar[LNLSTDENS][i] = lnNdens[i];

                        // clear out our integration variables if it's
                        // the first pass

                        if (data->freq ==
                            ((NOISEAN*)ckt->CKTcurJob)->NstartFreq) {

                            for (int i = 0; i < JFET2NSRCS; i++) {
                                inst->JFET2nVar[OUTNOIZ][i] = 0.0;
                                inst->JFET2nVar[INNOIZ][i] = 0.0;
                            }
                        }
                    }
                    else {
                        // data->delFreq != 0.0 (we have to integrate)

                        for (int i = 0; i < JFET2NSRCS; i++) {
                            if (i != JFET2TOTNOIZ) {
                                double tempOnoise;
                                double tempInoise;
                                tempOnoise = data->integrate(noizDens[i],
                                    lnNdens[i], inst->JFET2nVar[LNLSTDENS][i]);
                                tempInoise = data->integrate(noizDens[i]*
                                    data->GainSqInv,
                                    lnNdens[i] + data->lnGainInv,
                                    inst->JFET2nVar[LNLSTDENS][i] +
                                    data->lnGainInv);
                                inst->JFET2nVar[LNLSTDENS][i] = lnNdens[i];
                                data->outNoiz += tempOnoise;
                                data->inNoise += tempInoise;
                                if (((NOISEAN*)ckt->CKTcurJob)->NStpsSm != 0) {
                                    inst->JFET2nVar[OUTNOIZ][i] += tempOnoise;
                                    inst->JFET2nVar[OUTNOIZ][JFET2TOTNOIZ] +=
                                        tempOnoise;
                                    inst->JFET2nVar[INNOIZ][i] += tempInoise;
                                    inst->JFET2nVar[INNOIZ][JFET2TOTNOIZ] +=
                                        tempInoise;
                                }
                            }
                        }
                    }
                    if (data->prtSummary) {
                        for (int i = 0; i < JFET2NSRCS; i++) {
                            // print a summary report
                            data->outpVector[data->outNumber++] = noizDens[i];
                        }
                    }
                }
            }
            return (OK);
        }

        if (mode == INT_NOIZ) {
            // already calculated, just output
            if (static_cast<NOISEAN*>(ckt->CKTcurJob)->NStpsSm == 0)
                return (OK);
            for ( ; model; model = model->next()) {
                sJFET2instance *inst;
                for (inst = model->inst(); inst; inst = inst->next()) {

                    for (int i = 0; i < JFET2NSRCS; i++) {
                        data->outpVector[data->outNumber++] =
                            inst->JFET2nVar[OUTNOIZ][i];
                        data->outpVector[data->outNumber++] =
                            inst->JFET2nVar[INNOIZ][i];
                    }
                }
            }
        }
    }
    return (OK);
}

