#! /bin/sh

# Create the Makefile by copying the template and substituting text.

# cap
SOURCE=cap.va
MODELNAME=cap
MODULE=cap
KEY=c
LEVEL=2
ADD_M=no
LIMITING=no
FLAGS=

cat ../../Makefile | sed \
  -e "s%^SOURCE = .*%SOURCE = $SOURCE%" \
  -e "s%^MODELNAME = .*%MODELNAME = $MODELNAME%" \
  -e "s%^MODULE = .*%MODULE = $MODULE%" \
  -e "s%^KEY = .*%KEY = $KEY%" \
  -e "s%^LEVEL = .*%LEVEL = $LEVEL%" \
  -e "s%^ADD_M = .*%ADD_M = $ADD_M%" \
  -e "s%^LIMITING = .*%LIMITING = $LIMITING%" \
  -e "s%^FLAGS = .*%FLAGS = $FLAGS%" \
  > Makefile

