#! /bin/sh

#-----------------------------------------------------------------------------
# Whiteley Research Inc. proprietary software, not for public release.
#
# ADDPW: Add an access password to the database.
# Arguments:
#   $1 username (required)
#      The user to add.
#   $2 months (required)
#      Lifetime of password in months (0 means forever).
#   $3 password (optional)
#      Give a password to use, instead of creating one.
#
# Output:
#   ./.new_password file will contain the new user/password.
#   The database will be updated.
#   The .new_password line for username is echoed.
#
# $Id: addpw,v 1.2 2016/02/03 18:09:28 stevew Exp $
#-----------------------------------------------------------------------------

if [ $# != 2 -a $# != 3 ]; then
    echo "Usage: addpw user months [password]"
    exit 1;
fi

user=$1
months=$2
passw=$3

# Where the ppw installation lives.
targdir=/home/webadmin/wrcad.com/ppw

userchk=`$targdir/ppw check $user`
if [ x"$userchk" = xno ]; then
    # User is not in the database.

    # Assign a new password, save in ".new_password" file.
    if [ x$passw = x ]; then
        password=`$targdir/gpw/gpw 1 8`
    else
        password=$passw
    fi
    echo user: $user  password: $password >> $targdir/.new_password
    echo user: $user  password: $password

    # Obtain the encoded password from Apache.  Only the encoded password
    # is saved in the database.  The ".new_password" file is the only
    # record of the actual password.
    #
    str=`htpasswd -bn $user $password`
    tifs=$IFS
    IFS=":"
    set -- $str
    IFS=$tifs
    encpw=$2

    $targdir/ppw add $user $encpw $months

    if [ $? != 0 ]; then
        echo "FOO! ppw add failed!"
        exit 1
    fi

elif [ x"$userchk" = xyes ]; then
    # User is already in the database, just update months.

    $targdir/ppw refresh $user $months

    if [ $? != 0 ]; then
        echo "FOO! ppw add failed!"
        exit 1
    fi

    while read -r; do
        line=$REPLY
        set -- $line
        if [ $2 = $user ]; then
            echo $line
            break;
        fi;
    done < $targdir/.new_password

else
    echo "Database check user query returned error message."
    exit 1
fi

