# Makefile for build with system cminpack on CentOS 7.

mmjco: libmmjco.a main.cc
	g++ -o mmjco main.cc -L. -lmmjco -lgsl -lgslcblas -lcminpack -lm

libmmjco.a: mmjco.cc mmjco.h
	g++ -g -O -I/usr/include/cminpack-1 -c mmjco.cc
	ar -cr libmmjco.a mmjco.o
	ranlib libmmjco.a

clean::
	-@rm -f libmmjco.a *.o mmjco tca*.fit tca*.data
